### ISSUE TITLE
#Beginner (very noob) / Kingston DC500M or other enterprise kingstons

### ISSUE THREAD

**Issue by BIGOREGANO** [linux-nvme/nvme-cli#1015]
Hello, I'm gathering information to make a Chia mining rig, and I saw the following link:
https://github.com/Chia-Network/chia-blockchain/wiki/SSD-Endurance

Why don't they have any Kingston SSD's?

**Comment by keithbusch** [comment]
I suppose the owner of that project just didn't have any. The link you provided says they will add more models to their table if you want to provide the information.
