### ISSUE TITLE
NVMe status: INVALID_OPCODE: The associated command opcode field is not valid(0x4001)

### ISSUE THREAD

**Issue by MilesBHuff** [linux-nvme/nvme-cli#1024]
When issuing `nvme delete-ns -n 1 /dev/nvme0`, I get: `NVMe status: INVALID_OPCODE: The associated command opcode field is not valid(0x1)`.  This is for a WD Black (`WDS100T2X0C`).  I can find no way to update its firmware;  it's running something from at least 3 years ago.

When issuing `nvme delete-ns -n 1 /dev/nvme1`, I get: `NVMe status: INVALID_OPCODE: The associated command opcode field is not valid(0x4001)`.  This is for a Samsung 970 EVO (`MZ-V7E1T0BW`).  Its firmware is up-to-date, but was released 2 years ago.

From what I've seen in other issues here, it sounds like the above are probably firmware issues.  However, it seems maybe ¿wrong? that *both* my NVMe drives would fail the same operation like this, unless it's rare for consumer SSDs to support it.  I decided to post this issue in case these somehow *aren't* firmware issues, or in case you know something I can try.

(I'm trying to delete the default namespace on each drive, and create 2 namespaces on each:  one to give to ZFS, and one to use for the ESP and swap.  (ZFS behaves differently (better) when given a whole "disk", and namespaces would let me do that without compromising on the other partitions I want.)  I'm also hoping to overprovision by leaving a certain percentage of space outside a namespace.)

**Comment by birkelund** [comment]
I'm pretty sure none of those devices support Namespace Management. Try

    # nvme id-ctrl /dev/nvme0 -H | grep 'NS Management'

**Comment by MilesBHuff** [comment]
Ah, bless.  Thanks for the extremely quick reply.  Sure enough, when I run that on each drive, I get : `  [3:3] : 0     NS Management and Attachment Not Supported`.  Guess I'll just make due without.
