### ISSUE TITLE
OS X install?

### ISSUE THREAD

**Issue by drewwells** [linux-nvme/nvme-cli#1030]
This library depends on linux/types.h. Is it possible to compile it for darwin?

**Comment by keithbusch** [comment]
the implementation here is tightly coupled to the interfaces exposed by the Linux kernel, I'm not sure it would work well in OSX even if we resolve the header dependencies.

**Comment by igaw** [comment]
Question got answered.

BTW, in the meantime the code base has been spitted into nvme-cli and libnvme. In libnvme the type definition and the 'ioctl' are separated. So in theory if someone wants to port it to a different platform there is the starting point.
