### ISSUE TITLE
Test script for the end to end data protection feature of  NVMe 

### ISSUE THREAD

**Issue by ghost** [linux-nvme/nvme-cli#105]
Hi all maintainers and contributors, 

My name is Yongseok Oh, working on developing firmware S/W for NVMe SSDs at SK telelecom in South Korea. I believe the end to end data protection feature is very important in enterprise class storage systems. However, it is hard to find a test methodology and script for this issue. As a result, I decided to develop a test script using the NVMe CLI tool. This is very helpful and useful to evaluate and test this feature when developing NVMe SSDs. 

Please, review and have it included in your project. 
(https://github.com/DrYSOH/nvme-cli)

Yongseok Oh

**Comment by DrYSOH** [comment]
The changes have been committed to the e2edptest branch (https://github.com/DrYSOH/nvme-cli/tree/e2edptest)

**Comment by keithbusch** [comment]
Thanks, this looks very useful!

The devices I currently have only have a subset of what this is capable of testing, but it looks successful for what it can run. I'll review the rest this week and either apply or send additional feedback.

**Comment by yongseokoh** [comment]
My username has been changed from DrYSOH to yongseokoh.

**Comment by igaw** [comment]
No progess in this bug report for a long time. If you think it's still relevant please reopen.
