### ISSUE TITLE
How do I get the latency of nvme io-passthru command?

### ISSUE THREAD

**Issue by minimm** [linux-nvme/nvme-cli#1068]
Hi,

How do I get the latency of nvme io-passthru command? Whether only read and write commands get the command response time?

Thanks.

**Comment by keithbusch** [comment]
Add the --latency parameter in your read or write command.

**Comment by minimm** [comment]
I want to get the latency of the vendor command by nvme io-passthru. But I did not find the --latency parameter in nvme io-passthru.

**Comment by keithbusch** [comment]
You should have said that initially instead of saying read or write. The generic io-passthru doesn't have a latency option.

**Comment by ganaidu707** [comment]
I have added latency parameter for the passthru commands: https://github.com/linux-nvme/nvme-cli/pull/1072

**Comment by igaw** [comment]
The question got answered. Closing issue.
