### ISSUE TITLE
Invalid opcode for the reservation release command

### ISSUE THREAD

**Issue by DrYSOH** [linux-nvme/nvme-cli#110]
Hi maintainers, 

I found and fixed invalid opcode used in the nvme_resv_release() function. Please review and have it included in your project. 

(https://github.com/DrYSOH/nvme-cli/tree/resv_release_fix)

Yongseok Oh

**Comment by keithbusch** [comment]
You're right, I'll pull your fix in. Thanks for the note. I guess reservations haven't been a very common test!

**Comment by keithbusch** [comment]
Cherry-picked fix here: https://github.com/linux-nvme/nvme-cli/commit/f1e2ecb9315b1bbdc0830c00684ad8ea860e32cc

Thanks!
