### ISSUE TITLE
CDW2 and CDW3 fields needs to be added in nvme_user_io struct

### ISSUE THREAD

**Issue by ganaidu707** [linux-nvme/nvme-cli#1100]
as per 2.0 Spec in nvme_user_io  struct CDW2 and CDW3 fields support to be added, for `NVM commands Write, Read, Compare`.

Is there any plans to add this support in kernel?

```
struct nvme_user_io {
	__u8	opcode;
	__u8	flags;
	__u16	control;
	__u16	nblocks;
	__u16	rsvd;
	__u64	metadata;
	__u64	addr;
	__u64	slba;
	__u32	dsmgmt;
	__u32	reftag;
	__u16	apptag;
	__u16	appmask;
};
```

**Comment by keithbusch** [comment]
I think this struct is deprecated. If the kernel we depend on to create these commands isn't going to adapt, then neither should tooling.
