### ISSUE TITLE
nvme discover displaying spaces inside JSON oputput

### ISSUE THREAD

**Issue by KKaras169169** [linux-nvme/nvme-cli#1117]
I am using [SPDK](https://github.com/spdk/spdk) and calling a nvme discover command:
_sudo ./nvme discover -t tcp -a 151.0.0.123 -s 4420 -o json_
which yields following result:

![image](https://user-images.githubusercontent.com/49611974/126782433-8b0aef20-14e1-431c-b28c-03511db50f99.png)

There are a lot of whitespaces behind trsvcid and traddr values. The NVM Express Base Specification 2.0 states:
_"Transport Address (TRADDR): Specifies the address of the NVM subsystem that may be used
for a Connect command as an ASCII string. The Address Family field describes the reference for
parsing this field. Refer to section 1.4.2 for ASCII string requirements. For the definition of this
field, refer to the appropriate NVMe Transport binding specification."_ 

and in the 1.4.2 section we can find the following:
_"The string is left justified and shall be padded with spaces (ASCII character 20h) to the right if necessary."_ - meaning strings must be padded with spaces if necessary.

Could these additional spaces be trimmed on the nvme-cli side when outputting the final JSON?

**Comment by keithbusch** [comment]
sure, I think that's reasonable. i'll add it in.
