### ISSUE TITLE
NVMe status: INTERNAL: The command was not completed successfully due to an internal error(0x4006) seen while updating drive

### ISSUE THREAD

**Issue by sarabjotsoit** [linux-nvme/nvme-cli#1118]
NVMe status: INTERNAL: The command was not completed successfully due to an internal error(0x4006) seen while updating drive

**Comment by birkelund** [comment]
Yes, that is an Internal Device Error (status code 0x6) reported by the drive. You should report it to your vendor :)

**Comment by igaw** [comment]
Nothing we can do here. Closing the issue.
