### ISSUE TITLE
Add ccan support

### ISSUE THREAD

**Issue by igaw** [linux-nvme/nvme-cli#1203]
With the recent build refactoring in libnvme and header cleanups, le64_to_cpu & friends are not exported anymore. That means nmve-cli needs to use their own version of these helpers.  Anyway, ccan is a handy toolset let's add it in the main project and use the helpers from the ccan library.

**Comment by jk-ozlabs** [comment]
I'm interested in having a look, but this is just a free-time thing for me - if you're able to dedicate a bit of time to it, you'll probably get it done much faster!

**Comment by igaw** [comment]
Ah, yes, you are right. I got confused (again).
