### ISSUE TITLE
nvme id-ctrl  -  application crashes

### ISSUE THREAD

**Issue by abevis** [linux-nvme/nvme-cli#1218]
Hello,

while executing "sudo nvme id-ctrl /dev/nvme0n1" I am facing multiple issues
I am executing this on a laptop running ubuntu 20.04 

These are the errors I get - i don't get them all the time but few of the times and it's only either one of these errors
1. segmentation fault
2. Inconsistency detected by ld.so: dl-fini.c: 87: _dl_fini: Assertion `ns != LM_ID_BASE || i == nloaded' failed!
4. stack thrashing detected

What could be going wrong here?

**Comment by abevis** [comment]
Issue is resolved. Incorrect handling of unaligned address in devic. Thanks for your help

**Comment by keithbusch** [comment]
> is it right to be declaring the nvme structure locally (stack) - would this might cause some other alignment issues

Stack variable is fine. Nvme protocol requires devices support at least 8 byte alignment. If user space passes address that isn't aligned to that, the block layer will provide a sufficiently aligned bounce buffer.
