### ISSUE TITLE
nvme make failed on centos7 and ubuntu12 platform

### ISSUE THREAD

**Issue by jinhua2021** [linux-nvme/nvme-cli#1225]
Does nvme support centos7 and ubuntu12? It always failed with libnvme errors.
I had already submodule updated.

**Comment by igaw** [comment]
Can you add some more details to your bu report? Are you building the master branch or nvme-cli-monolithic? Can you post your commands you enter and also the log output?

**Comment by sc108-lee** [comment]
@jinhua2021  Centos build failure will be fixed soon :)
It will be able to build after merge blow PR
https://github.com/linux-nvme/nvme-cli/pull/1253
https://github.com/linux-nvme/libnvme/pull/131

**Comment by jinhua2021** [comment]
@sc108-lee @igaw 
Thanks, waiting for that:)

**Comment by igaw** [comment]
The two PR mentioned by @sc108-lee have been merged. Closing bug report. If it's still a problem, please reopen and some logs. Thanks.
