### ISSUE TITLE
Build fails on RHEL 8.5

### ISSUE THREAD

**Issue by mvogt1** [linux-nvme/nvme-cli#1260]
I tried to build current git and get the error:

make[1]: Leaving directory '/var/tmp/martin/nvme-cli/libnvme'
    CC nvme-print.o
nvme-print.c: In function ‘json_nvme_id_ns’:
nvme-print.c:164:2: error: implicit declaration of function ‘json_object_add_value_uint64’; did you mean ‘json_object_add_value_uint’? [-Werror=implicit-function-declaration]
  164 |  json_object_add_value_uint64(root, "nsze", le64_to_cpu(ns->nsze));
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |  json_object_add_value_uint
cc1: all warnings being treated as errors
make: *** [Makefile:151: nvme-print.o] Error 1

**Comment by sc108-lee** [comment]
try with #1261 fix?

**Comment by mvogt1** [comment]
It works even without the patch. The reason is, I though that nvme comes with its own json "util/json.h"
implemenation and uses this. But I was wrong. nvme needs a json from the system and if this fails I get the error above. This patch makes clear that a system json version is needed.
[json.txt](https://github.com/linux-nvme/nvme-cli/files/7625740/json.txt)

**Comment by BarisTuncer** [comment]
I had the same issue on ubuntu, installing json-c fixed the error I got: https://github.com/json-c/json-c#buildunix

**Comment by arthurshau** [comment]
I am having this issue as well on CentOS 8.
Version: json-c-0.13.1-2.el8.x86_64

**Comment by sc108-lee** [comment]
@mvogt1 you were right, it caused from util/json
checkout blow command, will fix this issue
https://github.com/linux-nvme/nvme-cli/pull/1268/commits/bcd0817efa51a75b95e015f97f949806eec98e16

**Comment by igaw** [comment]
As indicated by @sc108-lee this should be fixed. Closing bug report.
