### ISSUE TITLE
Show error message instead of error code

### ISSUE THREAD

**Issue by igaw** [linux-nvme/nvme-cli#1319]
Show error messages for the newly added libnvme's error codes.

instead
> failed to connect controller, error 1006

it should be
> failed to connect controller: failed to write to nvme-fabrics device

**Comment by hreinecke** [comment]
Just pushed https://github.com/linux-nvme/libnvme/pull/117 which adds a function nvme_errno_to_string().

**Comment by igaw** [comment]
Way better than my hacky first version1

**Comment by hreinecke** [comment]
PR merged.
