### ISSUE TITLE
dsm command not working on Ubuntu 12.04/14.04

### ISSUE THREAD

**Issue by kpooja88** [linux-nvme/nvme-cli#132]
Trying to issue dsm command on Ubuntu, and it fails with error code ffffffff, works on red hat however..

**Comment by keithbusch** [comment]
what version of ubuntu?

**Comment by keithbusch** [comment]
Oops, it's in the subject.

We didn't have passthrough IO commands until kernel revision 3.19. RH backported some of these to other releases. That should be Ubuntu 15.04.

**Comment by kpooja88** [comment]
Thanks!
