### ISSUE TITLE
70-nvmf-autoconnect.rules: Path to systemctl is hard coded

### ISSUE THREAD

**Issue by igaw** [linux-nvme/nvme-cli#1348]
The path to systemctl is hard coded to `/bin/systemctl`. Many distribution have merged the `/bin` and `/sbin` into `/usr/bin` or `/usr/sbin`. That means the hard coded path probably be changed to something more reasonable. Currently I do the following for openSUSE packaging: 

`sed -i 's;/bin/systemctl;/usr/bin/systemctl;g' %{buildroot}%{_udevrulesdir}/70-nvmf-autoconnect.rules`

**Comment by hreinecke** [comment]
Fixed by PR ##1431.
