### ISSUE TITLE
Structure returned by nvme list-ns is not correct

### ISSUE THREAD

**Issue by kpooja88** [linux-nvme/nvme-cli#135]
list-ns returns a lot of garbage data, probably for the unused buffer space...is this correct? Or am I interpreting the returned data structure wrong.?

**Comment by keithbusch** [comment]
Looks fine on my machines. What are you observing?

**Comment by kpooja88** [comment]
This seems to be an issue on my end..sorry about that..closing this issue. Thanks for the immediate response!
