### ISSUE TITLE
nvme disconnect执行时间特别长， 堆栈信息卡在 __ib_drain_sq上面

### ISSUE THREAD

**Issue by tongjingen** [linux-nvme/nvme-cli#1365]
nvme disconnect一个映射执行时间20分钟才结束(rdma的传输方式)

进程stack：

__ib_drain_sq
ib_drain_sq
nvme_rdma_stop_queue
...

target: disconnect host from subsystem xxx due to keep alive timeout

**Comment by igaw** [comment]
Unfortunately, I don't understand what you are writing and Google translate didn't help either.

It looks though you are reporting a kernel crash. nvme_rdma_stop_queue is definitely a kernel function. But I can't really say anything than this.
