### ISSUE TITLE
NVME List Output JSON Segmentation Fault

### ISSUE THREAD

**Issue by Teumer** [linux-nvme/nvme-cli#140]
environment
1. nvme-cli version 1.0
2. ubuntu 14.04.5 kernel 4.1.10

steps to reproduce
1. make && make install
2. nvme list --output-format=json
3. returns "Segmentation fault"
> dmesg
[ 2947.885599] nvme[26026]: segfault at 0 ip 00007f74d1274ebc sp 00007ffd8ffd6820 error 4 in libc-2.19.so[7f74d1206000+1ba000]
[ 2974.819305] nvme[27464]: segfault at 0 ip 00007f31ac4b9ebc sp 00007ffd5c36a410 error 4 in libc-2.19.so[7f31ac44b000+1ba000]
[ 3054.771953] nvme[29480]: segfault at 0 ip 00007f1df528debc sp 00007fff24d03850 error 4 in libc-2.19.so[7f1df521f000+1ba000]

Note other commands formatted w/ json output work w/o issue (only nvme list has the fault)
1. nvme id-ctrl /dev/nvme0 --output-format=json
2. nvme fw-log /dev/nvme0n1 -o json

**Comment by keithbusch** [comment]
hm, this is testing successfully here. How many nvme controllers do you have?

**Comment by Teumer** [comment]
6 total controllers

**Comment by keithbusch** [comment]
Okay, 6 appears to be the tipping point. Will have a fix by today.

**Comment by keithbusch** [comment]
oh, 6 was just a red herring on my machine. the real problem is the product name pulled from the models file, which may not be installed on every environment.

**Comment by keithbusch** [comment]
Fix pushed.
