### ISSUE TITLE
smart-log command doesn't support temperature below 0 degree c

### ISSUE THREAD

**Issue by nutanixperf** [linux-nvme/nvme-cli#141]
Could you please fix:

nvme-print.c
![image](https://cloud.githubusercontent.com/assets/21093200/20693134/31347686-b591-11e6-8ba4-deb48dc6cb7d.png)

**Comment by jderrick** [comment]
Relevant kernel discussion:
http://lists.infradead.org/pipermail/linux-nvme/2015-October/002598.html

**Comment by keithbusch** [comment]
The scsi translation is broken, but we don't have to use it for the native app. The unsigned usage has been fixed; thank you for raising the issue.
