### ISSUE TITLE
JSON string handling regression

### ISSUE THREAD

**Issue by martin-gpy** [linux-nvme/nvme-cli#1411]
Seems the JSON string handling has changed with the recent nvme-cli upgrade to v2.x in context of adding escape characters. For e.g. 

Prior to the v2.x upgrade:
Strings such as "/dev/nvme1n1" were permitted in the JSON output.

With the current v2.x:
Above string now shows up as "\\/dev\\/nvme1n1" in the JSON output.

This seems to be coming from util/json.c::json_create_value_string() which inserts a '\\' escape character whenever it encounters a '/' character in the string.

**Comment by igaw** [comment]
The JSON spec says you CAN escape forward slash, but you don't have to. Though it makes sense to keep the same pattern we already established.
