### ISSUE TITLE
how to create ns?

### ISSUE THREAD

**Issue by BruceHao123** [linux-nvme/nvme-cli#142]
the function about nvme_submit_admin_passthru in the ioctl.c how to excute in order to create ns?

**Comment by keithbusch** [comment]
The admin passthrough is for commands that are not defined in the spec. While you could use it for spec defined commands, it's not very user friendly.

Creating an ns is through the "create-ns" sub-command. See `nvme help create-ns` or `nvme create-ns --help` if you need some pointers on the command usage.

The majority of controllers on the market today do not support this optional command, though, so make sure your device is capable by verifying Identify Controller's OACS bit 4 is set. One way to check that: `nvme id-ctrl -H | grep "NS Management"`
