### ISSUE TITLE
Multiple persistent discovery

### ISSUE THREAD

**Issue by igaw** [linux-nvme/nvme-cli#1423]
@martin-gpy  reported:

> With the recent upgrade to nvme-cli v2.x, multiple persistent discovery
> controllers (PDCs) are now permitted to be created on the same initiator-target
> combo - in fact, it creates a new PDC every time the nvme discovery command is
> run with the -p option, leading to wastage of resources on both the initiator
> and target.
> 
> Ideally, if a PDC already exists, the same should be utilized instead of
> creating a new PDC each and every time the discovery command is run with the -p
> option.
> 
> Looks likes nvme-cli v2.x misses on the below commit from the monolithic
> branch, which should address this issue:
> 
> nvme-discover: lookup existing persistent controllers -
> https://github.com/linux-nvme/nvme-cli/commit/14d0e0f7e0c1b420da65783881c064e49ac7d6d7

**Comment by hreinecke** [comment]
Just validated it; works with most recent upstream.
