### ISSUE TITLE
JSON output key naming difference between 1.x and 2.0 series

### ISSUE THREAD

**Issue by tbzatek** [linux-nvme/nvme-cli#1424]
_(this is rather a question, might be an issue for somebody)_

Just noticed the key naming differences in verbose JSON ouput, compare:
https://github.com/linux-nvme/nvme-cli/blob/7ff90b5f5ff718f760b266c06eecdad359d86a28/nvme-print.c#L7102-L7115
vs.
https://github.com/linux-nvme/nvme-cli/blob/1264c6323937c4a0342174fdd9be5a66ab1eaf24/nvme-print.c#L6899-L6919

This might a concern to some consumers as they need to adapt their parsers. Differences between major versions are expected, though difficult to spot as the `nvme` commands and arguments are mostly consistent otherwise.

Sorry if this has been discussed previously, too lazy to search...

**Comment by hreinecke** [comment]
Hmm. Yeah, we should be consistent. Feel free to send a patch adjusting the JSON attributes to the 1.x version.
