### ISSUE TITLE
fused operations: eg.compare and write

### ISSUE THREAD

**Issue by coderaskanoter** [linux-nvme/nvme-cli#1438]
can it send a fused operation(eg.compare and write fused operation) by nvme cli. If it can, can you give me a example of caw command?

**Comment by keithbusch** [comment]
No, the kernel doesn't support it. We would be depending on the low level driver to dispatch fused commands in consecutive slots of the same queue, and it doesn't provide any such mechanism.

**Comment by igaw** [comment]
Closing. There is not much we can do unless we have support from the kernel for this.  There were some attempts to get this feature working but it's not that simple see the discussion on the nvme mailing list:

  https://lore.kernel.org/linux-nvme/20210105224939.1336-2-clay.mayers@kioxia.com/T/
