### ISSUE TITLE
nvme-cli add locate LED、 prepare-for-removal fustion

### ISSUE THREAD

**Issue by 512868516** [linux-nvme/nvme-cli#146]
hgst nvme manager tool：hdm。
hdm have two fuction that was very useful：
hdm locate               Enables or disables the LED beacon for physical devices.
hdm prepare-for-removal  Prepares physical devices for safe removal from the system

do you have any plan to add locate LED and  prepare-for-removal  fuction？

**Comment by keithbusch** [comment]
There's no such thing as an NVMe defined way for LED control. Any such thing would be specific to hardware. If you want to submit a 3rd party plugin for such, that's okay with me.

**Comment by keithbusch** [comment]
At the moment, this is simply not an nvme feature. Current LED solutions are vendor and/or platform specific at this time; closing as this tool is not for tracking such issues.
