### ISSUE TITLE
Meson Subproject Download Failure

### ISSUE THREAD

**Issue by jeffreyalien** [linux-nvme/nvme-cli#1491]
Is there a minimum git level required for the meson build process to work successfully?   I'm seeing this failure on a system with git version 1.8.3.1 and it works fine on a different system with git version 2.27.0.  I've attached the full make output file from this failure.

Run-time dependency libnvme found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency libnvme
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

meson.build:34:0: ERROR: Git command failed

meson.build line 34:
libnvme_dep = dependency('libnvme', fallback : ['libnvme', 'libnvme_dep'])

The command "meson subprojects download" also fails with the same "Unknown option: -C" message.   I don't see a -C option in the "git clone" command on either system so I'm not exactly sure what git command is being executed here. 

[mesonMakeFailure.txt](https://github.com/linux-nvme/nvme-cli/files/8454357/mesonMakeFailure.txt)

**Comment by igaw** [comment]
'-C' argument was introduced int git with  44e1e4d67d51 ("git: run in a directory given with -C option") and released with git v1.8.5.  Your git version is too old.
