### ISSUE TITLE
Update URL to HTTPS

### ISSUE THREAD

**Issue by TotalCaesar659** [linux-nvme/nvme-cli#1506]
Please update URL to HTTPS for security reasons.
![0](https://user-images.githubusercontent.com/14265316/163570010-e048356c-d8b5-41fc-85fa-054f46aa420f.png)

**Comment by igaw** [comment]
@keithbusch could you update the link? Or alternative you give me the permission to do so :)

**Comment by keithbusch** [comment]
Sure, I can't figure bout how to do it from the mobile interface, but I'll try to fix the link when I get home later.

**Comment by keithbusch** [comment]
Done.

**Comment by keithbusch** [comment]
> Or alternative you give me the permission to do so :)

Oh, and I've set your permissions to "Admin" (that's the highest it will let me :)).
