### ISSUE TITLE
nvme connect-all -C option is broken

### ISSUE THREAD

**Issue by martin-gpy** [linux-nvme/nvme-cli#1521]
The nvme connect-all -C option for reading the config JSON file and applying the respective values here during the connect-all is also broken (similar to the nvme connect -J option failing as tracked in #1520). For e.g.

$ cat /etc/nvme/discovery.conf
 --transport=tcp --traddr=192.168.1.116 --host-traddr=192.168.1.16
 --transport=tcp --traddr=192.168.1.117 --host-traddr=192.168.1.16
 --transport=tcp --traddr=192.168.2.116 --host-traddr=192.168.2.16
 --transport=tcp --traddr=192.168.2.117 --host-traddr=192.168.2.16

$ ls /etc/nvme/config.json
ls: cannot access '/etc/nvme/config.json': No such file or directory

Even with no config JSON file available at /etc/nvme/config.json, nvme connect-all is still successful even after specifying the non-existent JSON file here:

$ nvme connect-all -C /etc/nvme/config.json
$

And even after we create and populate the /etc/nvme/config.json as follows:

$ cat /etc/nvme/config.json
[
  {
    "hostnqn":"nqn.2014-08.org.nvmexpress:uuid:12372496-59c4-4d1b-be09-74362c0c1afc",
    "hostid":"59de25be-7383-48f0-8a79-df4bce9573f3",
    "subsystems":[
      {
        "nqn":"nqn.1992-08.com.netapp:sn.48391d66c0a611ecaaa5d039ea165514:subsystem.subsys_CLIENT116",
        "ports":[
          {
            "transport":"tcp",
            "traddr":"192.168.2.117",
            "host_traddr":"192.168.2.16",
            "trsvcid":"4420",
             "keep_alive_tmo": "45",
             "hdr_digest": true
          },
          {
            "transport":"tcp",
            "traddr":"192.168.2.116",
            "host_traddr":"192.168.2.16",
            "trsvcid":"4420",
             "keep_alive_tmo": "45",
             "hdr_digest": true
          },
          {
            "transport":"tcp",
            "traddr":"192.168.1.117",
            "host_traddr":"192.168.1.16",
            "trsvcid":"4420",
             "keep_alive_tmo": "45",
             "hdr_digest": true
          },
          {
            "transport":"tcp",
            "traddr":"192.168.1.116",
            "host_traddr":"192.168.1.16",
            "trsvcid":"4420",
             "keep_alive_tmo": "45",
             "hdr_digest": true
          }
        ]
      }
    ]
  }
]

nvme connect-all is successful, but does not pick up the values from the above config JSON file:

$ nvme connect-all -C /etc/nvme/config.json
$

Turns out it completely ignores the above config JSON file, and instead only reads the /etc/nvme/discovery.conf, fetches the discovery log page data and proceeds to connect to each of the subsystems listed here with the default values itself i.e. it completely ignores the values specified in the JSON file above:

$ nvme list-subsys /dev/nvme1n1
nvme-subsys1 - NQN=nqn.1992-08.com.netapp:sn.48391d66c0a611ecaaa5d039ea165514:subsystem.subsys_CLIENT116
\
 +- nvme1 tcp traddr=192.168.1.117,trsvcid=4420,host_traddr=192.168.1.16 live non-optimized
 +- nvme2 tcp traddr=192.168.1.116,trsvcid=4420,host_traddr=192.168.1.16 live optimized
 +- nvme3 tcp traddr=192.168.2.117,trsvcid=4420,host_traddr=192.168.2.16 live non-optimized
 +- nvme4 tcp traddr=192.168.2.116,trsvcid=4420,host_traddr=192.168.2.16 live optimized

$ cat /sys/class/nvme-subsystem/nvme-subsys1/nvme1/kato
5
$ cat /sys/class/nvme-subsystem/nvme-subsys1/nvme2/kato
5
$ cat /sys/class/nvme-subsystem/nvme-subsys1/nvme3/kato
5
$ cat /sys/class/nvme-subsystem/nvme-subsys1/nvme4/kato
5

**Comment by igaw** [comment]
It's `nvme connect-all -J config.json` and not `nvme connect-all -C config.json` which matches the `nvme connect -J config.json` command line options.
