### ISSUE TITLE
Create block device per character device

### ISSUE THREAD

**Issue by LiadOz** [linux-nvme/nvme-cli#1530]
I have a use case in which I want to create a block device per ip so that I would have a complete control over what ip will communicate with a namespace. Is this feature implemented in the tool? If not does implementing such a feature feasible?

I have a workaround which is to create for each port a new hostnqn and configure the target accordingly, in this case every ip will get a new block device, but this solution would probably be too volatile.

**Comment by igaw** [comment]
The kernel is in charge of the block devices, this is not something nvme-cli is controlling. I think your current setup is the way to get the kernel convinced to create a block device per IP. 

Though one thing to checkout out is that  you can tell the kernel which networking interface should be use to communicate with the target. So you could setup VLANs and tell via `nvme connect -w HOST_IPADDR ...` which path to use. But still you need to setup the target accordingly.
