### ISSUE TITLE
Not building with "undeclared" error in nvme.c and nvme-print.c

### ISSUE THREAD

**Issue by Nitheesh1609** [linux-nvme/nvme-cli#1551]
Below is the output for ninja -C build command. I am using meson 0.62.1 and ninja 1.10.2. I am not sure why is this undeclared error? Most of them are from the latest merge ( commit: bcda657c812f765fa831a4b0766ba64cc85eb6df) which was updated yesterday.

[root@localhost nvme-cli]# ninja -C .build
ninja: Entering directory `.build'
[20/53] Compiling C object nvme.p/nvme-print.c.o
FAILED: nvme.p/nvme-print.c.o
cc -Invme.p -I. -I.. -Iccan -I../ccan -Isubprojects/json-c-0.15 -I../subprojects/json-c-0.15 -I/usr/include/json-c -I/usr/include/uuid -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -O3 -fomit-frame-pointer -D_GNU_SOURCE -include config.h -pthread -MD -MQ nvme.p/nvme-print.c.o -MF nvme.p/nvme-print.c.o.d -o nvme.p/nvme-print.c.o -c ../nvme-print.c
../nvme-print.c: In function ‘nvme_show_registers_cc’:
../nvme-print.c:2617:3: warning: implicit declaration of function ‘NVME_CC_CRIME’; did you mean ‘NVME_CC_AMS’? [-Wimplicit-function-declaration]
 2617 |   NVME_CC_CRIME(cc) ? "Enabled":"Disabled");
      |   ^~~~~~~~~~~~~
      |   NVME_CC_AMS
../nvme-print.c: In function ‘nvme_show_registers_crto’:
../nvme-print.c:2670:3: warning: implicit declaration of function ‘NVME_CRTO_CRIMT’ [-Wimplicit-function-declaration]
 2670 |   NVME_CRTO_CRIMT(crto)/2 );
      |   ^~~~~~~~~~~~~~~
../nvme-print.c:2672:3: warning: implicit declaration of function ‘NVME_CRTO_CRWMT’ [-Wimplicit-function-declaration]
 2672 |   NVME_CRTO_CRWMT(crto)/2 );
      |   ^~~~~~~~~~~~~~~
../nvme-print.c: In function ‘json_ctrl_registers’:
../nvme-print.c:2925:27: error: ‘NVME_REG_CRTO’ undeclared (first use in this function); did you mean ‘NVME_REG_CSTS’?
 2925 |  crto = mmio_read32(bar + NVME_REG_CRTO);
      |                           ^~~~~~~~~~~~~
      |                           NVME_REG_CSTS
../nvme-print.c:2925:27: note: each undeclared identifier is reported only once for each function it appears in
../nvme-print.c: In function ‘nvme_show_ctrl_registers’:
../nvme-print.c:2996:27: error: ‘NVME_REG_CRTO’ undeclared (first use in this function); did you mean ‘NVME_REG_CSTS’?
 2996 |  crto = mmio_read32(bar + NVME_REG_CRTO);
      |                           ^~~~~~~~~~~~~
      |                           NVME_REG_CSTS
../nvme-print.c: In function ‘nvme_show_single_property’:
../nvme-print.c:3185:7: error: ‘NVME_REG_CRTO’ undeclared (first use in this function); did you mean ‘NVME_REG_CSTS’?
 3185 |  case NVME_REG_CRTO:
      |       ^~~~~~~~~~~~~
      |       NVME_REG_CSTS
[22/53] Compiling C object nvme.p/nvme.c.o
FAILED: nvme.p/nvme.c.o
cc -Invme.p -I. -I.. -Iccan -I../ccan -Isubprojects/json-c-0.15 -I../subprojects/json-c-0.15 -I/usr/include/json-c -I/usr/include/uuid -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -O3 -fomit-frame-pointer -D_GNU_SOURCE -include config.h -pthread -MD -MQ nvme.p/nvme.c.o -MF nvme.p/nvme.c.o.d -o nvme.p/nvme.c.o -c ../nvme.c
../nvme.c: In function ‘format’:
../nvme.c:4810:4: error: ‘struct nvme_format_nvm_args’ has no member named ‘lbafu’; did you mean ‘lbaf’?
 4810 |   .lbafu  = (cfg.lbaf & NVME_NS_FLBAS_HIGHER_MASK) >> 4,
      |    ^~~~~
      |    lbaf
../nvme.c: In function ‘write_zeroes’:
../nvme.c:5543:35: error: ‘NVME_NVM_ELBAF_STS_MASK’ undeclared (first use in this function); did you mean ‘NVME_LBAF_RP_MASK’?
 5543 |   sts = nvm_ns.elbaf[lba_index] & NVME_NVM_ELBAF_STS_MASK;
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~
      |                                   NVME_LBAF_RP_MASK
../nvme.c:5543:35: note: each undeclared identifier is reported only once for each function it appears in
../nvme.c:5544:36: error: ‘NVME_NVM_ELBAF_PIF_MASK’ undeclared (first use in this function); did you mean ‘NVME_NS_DPS_PI_MASK’?
 5544 |   pif = (nvm_ns.elbaf[lba_index] & NVME_NVM_ELBAF_PIF_MASK) >> 7;
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~
      |                                    NVME_NS_DPS_PI_MASK
../nvme.c:5559:4: error: ‘struct nvme_io_args’ has no member named ‘reftag_u64’; did you mean ‘reftag’?
 5559 |   .reftag_u64 = cfg.ref_tag,
      |    ^~~~~~~~~~
      |    reftag
../nvme.c:5562:4: error: ‘struct nvme_io_args’ has no member named ‘sts’
 5562 |   .sts  = sts,
      |    ^~~
../nvme.c:5563:4: error: ‘struct nvme_io_args’ has no member named ‘pif’
 5563 |   .pif  = pif,
      |    ^~~
../nvme.c: In function ‘copy’:
../nvme.c:5727:29: error: array type has incomplete element type ‘struct nvme_copy_range_f1’
 5727 |   struct nvme_copy_range_f1 f1[101];
      |                             ^~
../nvme.c:5832:3: warning: implicit declaration of function ‘nvme_init_copy_range_f1’; did you mean ‘nvme_init_copy_range’? [-Wimplicit-function-declaration]
 5832 |   nvme_init_copy_range_f1(copy.f1, nlbs, (__u64 *)slbas,
      |   ^~~~~~~~~~~~~~~~~~~~~~~
      |   nvme_init_copy_range
../nvme.c:5850:4: error: ‘struct nvme_copy_args’ has no member named ‘ilbrt_u64’
 5850 |   .ilbrt_u64 = cfg.ilbrt,
      |    ^~~~~~~~~
../nvme.c: In function ‘submit_io’:
../nvme.c:6516:36: error: ‘NVME_NVM_ELBAF_STS_MASK’ undeclared (first use in this function); did you mean ‘NVME_LBAF_RP_MASK’?
 6516 |    sts = nvm_ns.elbaf[lba_index] & NVME_NVM_ELBAF_STS_MASK;
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~
      |                                    NVME_LBAF_RP_MASK
../nvme.c:6517:37: error: ‘NVME_NVM_ELBAF_PIF_MASK’ undeclared (first use in this function); did you mean ‘NVME_NS_DPS_PI_MASK’?
 6517 |    pif = (nvm_ns.elbaf[lba_index] & NVME_NVM_ELBAF_PIF_MASK) >> 7;
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~
      |                                     NVME_NS_DPS_PI_MASK
../nvme.c:6589:4: error: ‘struct nvme_io_args’ has no member named ‘sts’
 6589 |   .sts  = sts,
      |    ^~~
../nvme.c:6589:11: warning: excess elements in struct initializer
 6589 |   .sts  = sts,
      |           ^~~
../nvme.c:6589:11: note: (near initialization for ‘args’)
../nvme.c:6590:4: error: ‘struct nvme_io_args’ has no member named ‘pif’
 6590 |   .pif  = pif,
      |    ^~~
../nvme.c:6590:11: warning: excess elements in struct initializer
 6590 |   .pif  = pif,
      |           ^~~
../nvme.c:6590:11: note: (near initialization for ‘args’)
../nvme.c:6592:4: error: ‘struct nvme_io_args’ has no member named ‘reftag_u64’; did you mean ‘reftag’?
 6592 |   .reftag_u64 = cfg.ref_tag,
      |    ^~~~~~~~~~
      |    reftag
../nvme.c: In function ‘verify_cmd’:
../nvme.c:6770:35: error: ‘NVME_NVM_ELBAF_STS_MASK’ undeclared (first use in this function); did you mean ‘NVME_LBAF_RP_MASK’?
 6770 |   sts = nvm_ns.elbaf[lba_index] & NVME_NVM_ELBAF_STS_MASK;
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~
      |                                   NVME_LBAF_RP_MASK
../nvme.c:6771:36: error: ‘NVME_NVM_ELBAF_PIF_MASK’ undeclared (first use in this function); did you mean ‘NVME_NS_DPS_PI_MASK’?
 6771 |   pif = (nvm_ns.elbaf[lba_index] & NVME_NVM_ELBAF_PIF_MASK) >> 7;
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~
      |                                    NVME_NS_DPS_PI_MASK
../nvme.c:6786:4: error: ‘struct nvme_io_args’ has no member named ‘reftag_u64’; did you mean ‘reftag’?
 6786 |   .reftag_u64 = cfg.ref_tag,
      |    ^~~~~~~~~~
      |    reftag
../nvme.c:6789:4: error: ‘struct nvme_io_args’ has no member named ‘sts’
 6789 |   .sts  = sts,
      |    ^~~
../nvme.c:6790:4: error: ‘struct nvme_io_args’ has no member named ‘pif’
 6790 |   .pif  = pif,
      |    ^~~
[33/53] Compiling C object nvme.p/plugins_micron_micron-nvme.c.o
ninja: build stopped: subcommand failed.

**Comment by igaw** [comment]
You need to update libnvme, see https://github.com/linux-nvme/nvme-cli#meson-tips
