### ISSUE TITLE
set nvme ps0 to ps4,but the current doesn't change.

### ISSUE THREAD

**Issue by cljglll** [linux-nvme/nvme-cli#1580]
Hi, I 'm success to change power state of nvme from 0 to 4 with set feature command,but the current of the device is same as before.

In addition,I set power state of pcie from D0 to D1, or L0 to L1,the current of the device become low.

**Comment by igaw** [comment]
Which devices? Could you post the commands and log form the shell. And if there are kernel logs add them also.

**Comment by cljglll** [comment]
> Which devices? Could you post the commands and log form the shell. And if there are kernel logs add them also.

![image](https://user-images.githubusercontent.com/105629440/174921233-df202ab7-b3a9-4e2e-b3f2-73cfb12193b0.png)
![image](https://user-images.githubusercontent.com/105629440/174921369-8bf035f7-74f5-43bf-8ff5-9d5fca65092b.png)

**Comment by keithbusch** [comment]
Without seeing the power state descriptors, it's impossible to know what difference you might expect between ps0 and ps4.

**Comment by cljglll** [comment]
> Without seeing the power state descriptors, it's impossible to know what difference you might expect between ps0 and ps4.
![image](https://user-images.githubusercontent.com/105629440/174929710-778af7a5-46d2-4241-be3b-5764e0ee6c17.png)
![image](https://user-images.githubusercontent.com/105629440/174929779-48fdf19c-5cf3-46de-adc8-2f2f6df28d7c.png)
![image](https://user-images.githubusercontent.com/105629440/174929813-5f984315-e6e6-4de8-9c4d-e97631a72f07.png)
the NPSS and the power state descriptors may be OK。

**Comment by keithbusch** [comment]
The spec provides a lot of caveats that allow a controller to ignore a user request to a non-operational power state.

**Comment by cljglll** [comment]
> The spec provides a lot of caveats that allow a controller to ignore a user request to a non-operational power state.

I see the spec of nvme with V1.16,don't find the caveats.
NOPPME?this is set to 0.

**Comment by cljglll** [comment]
> > The spec provides a lot of caveats that allow a controller to ignore a user request to a non-operational power state.
> 
> I see the spec of nvme with V1.16,don't find the caveats. NOPPME?this is set to 0.
In addition,NOPPME is 0 , but the power consumption exceeds the limit of ps1 and ps2 when I set the power state to 1 or 2.

**Comment by keithbusch** [comment]
It sounds like your device may not be implementing the capability correctly. I think the hardware vendor may be in the best position to clarify.

**Comment by cljglll** [comment]
> It sounds like your device may not be implementing the capability correctly. I think the hardware vendor may be in the best position to clarify.

I see.
Thank you for your suggestion.

**Comment by keithbusch** [comment]
> I see the spec of nvme with V1.16,don't find the caveats.

The statements saying the controller can ignore user requested power states to support background activity pretty much gives the controller full discretion to ignore this feature.
