### ISSUE TITLE
where is the definition of function such as  nvme_identify_nvmset_list??

### ISSUE THREAD

**Issue by MagaretJi** [linux-nvme/nvme-cli#1582]
![image](https://user-images.githubusercontent.com/41857599/175008585-77fcc25a-06d7-4f50-91e2-aeed678f8159.png)
can not find!!

**Comment by igaw** [comment]
This function is part of libnvme: https://github.com/linux-nvme/libnvme/blob/13fe1108a0cfd83cd5f7280fb64e93e9c0a16218/src/nvme/ioctl.h#L675
