### ISSUE TITLE
nvme effects-log return 0 even if failed.

### ISSUE THREAD

**Issue by yizhanglinux** [linux-nvme/nvme-cli#1601]
Hi 
`nvme effects-log` return 0 even if failed with latest nvme-cli, but it return non-zero with `nvme version 1.16`, pls help to check it, thanks.

```
# ./nvme  --version
nvme version 1.16
# ./nvme effects-log /dev/nvme1n1
NVMe status: INVALID_LOG_PAGE: The log page indicated is invalid. This error condition is also returned if a reserved log page is requested(0x109)
# echo $?
22

With latest nvme-cli
# .build/nvme effects-log /dev/nvme1n1
NVMe status: Invalid Log Page: The log page indicated is invalid(0x109)
# echo $?
0
```

**Comment by igaw** [comment]
Thanks for the bug report. The error/status code was not forwarded to the shell anymore due to change in 155fbebfe7b7 ("Update effects-log to handle multiple command sets"). Should be fixed with PR #1603
