### ISSUE TITLE
zns report-zones don't work

### ISSUE THREAD

**Issue by sunxing0210** [linux-nvme/nvme-cli#1602]
when I send nvme zns report-zones /dev/nvme1 -n 1 -s 32 -S 15 -o json, always return error as below:
nvme: malloc.c:2516: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.

**Comment by igaw** [comment]
Do you happed to have a full backtrace from gdb: `bt full`?

**Comment by igaw** [comment]
BTW, build nvme-cli in debug mode. 

```shell
meson .build --builttype=debug
ninja -C .build
gdb --args .build/nvme zns report-zones /dev/nvme0 -n 1 -s 32 -S 15
```
and then type 'r' and when it crashes do a 'bt full'

**Comment by sunxing0210** [comment]
Starting program: /home/dapu/git/nvme-cli/.build/nvme zns report-zones /dev/nvme1 -n 1 -s 32 -S 15 -o json -d 1
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
nvme: malloc.c:2516: sysmalloc: Assertion `(old_top == initial_top (av) &amp;&amp; old_size == 0) || ((unsigned long) (old_size) &gt;= MINSIZE &amp;&amp; prev_inuse (old_top) &amp;&amp; ((unsigned long) old_end &amp; (pagesize - 1)) == 0)' failed.


Program received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737348147072) at pthread_kill.c:44
44&nbsp; &nbsp; &nbsp; pthread_kill.c: No such file or directory.







孙兴
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "linux-nvme/nvme-cli"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月11日(星期一) 晚上8:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [linux-nvme/nvme-cli] zns report-zones don't work (Issue #1602)





 
BTW, build nvme-cli in debug mode.
 meson .build --builttype=debug ninja -C .build gdb --args .build/nvme zns report-zones /dev/nvme0 -n 1 -s 32 -S 15
 
and then type 'r' and when it crashes do a 'bt full'

**Comment by sunxing0210** [comment]
This is my log:
***@***.***:/home/dapu/git/nvme-cli# /usr/sbin/nvme zns report-zones /dev/nvme1 -n 1 -s 32 -S 15 -o json -d 1
sizeof(struct nvme_zone_report) log_len:64
cfg.namespace_id:1, cfg.state:15, log_len:64
cfg.num_descs:1, total_nr_zones:63
nr_zones:1, nr_zones_chunks:1
report_size:128, zdes:0
getpagesize:4096




and when I not use "-d 1":
***@***.***:/home/dapu/git/nvme-cli# /usr/sbin/nvme zns report-zones /dev/nvme1 -n 1 -s 32 -S 15 -o json
sizeof(struct nvme_zone_report) log_len:64
cfg.namespace_id:1, cfg.state:15, log_len:64
cfg.num_descs:63, total_nr_zones:63
nr_zones:63, nr_zones_chunks:63
report_size:4096
getpagesize:4096





I think report_size maybe OK, and i find when run __nvme_alloc(){posix_memalign()}, error occurred.





孙兴
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "linux-nvme/nvme-cli"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月11日(星期一) 晚上9:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [linux-nvme/nvme-cli] zns report-zones don't work (Issue #1602)





 
Bummer, gdb seems not be able to provide a stack trace. I don't see where we crash.
 Well you could set a breakpoint on nvme_alloc in gdb (b nvme_alloc) and then do a
 bt full or try this here:
 diff --git a/plugins/zns/zns.c b/plugins/zns/zns.c index 0b96346fc30a..326b4e7c2436 100644 --- a/plugins/zns/zns.c +++ b/plugins/zns/zns.c @@ -955,6 +955,7 @@ static int report_zones(int argc, char **argv, struct command *cmd, struct plugi         log_len = sizeof(struct nvme_zone_report) + ((sizeof(struct nvme_zns_desc) * nr_zones_chunks) + (nr_zones_chunks * zdes));         report_size = log_len;   +       printf("report_size %u\n, report_size);         report = nvme_alloc(report_size, &amp;huge);         if (!report) {                 perror("alloc");
 
I assume the report_size argument is too large.

**Comment by igaw** [comment]
The pattern is
- fails with `-d 1`:
  `report_size: 128`
- succeeds without `-d 1`:
  `report_size: 4096`

**Comment by sunxing0210** [comment]
It's OK.


posix_memalign len=4088: success
posix_memalign len=4089: success
posix_memalign len=4090: success
posix_memalign len=4091: success
posix_memalign len=4092: success
posix_memalign len=4093: success
posix_memalign len=4094: success
posix_memalign len=4095: success
posix_memalign len=4096: success


It seems that func&nbsp;__nvme_alloc has no problem in nvme.c, but occur error......





孙兴
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "linux-nvme/nvme-cli"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月11日(星期一) 晚上10:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [linux-nvme/nvme-cli] zns report-zones don't work (Issue #1602)





 
Does this test program work on your system?
 #include <stddef.h&gt; #include <stdlib.h&gt; #include <stdio.h&gt; #include <unistd.h&gt; static void test(size_t len) { 	void *p; 	printf("posix_memalign len=%ld: ", len); 	if (!posix_memalign(&amp;p, getpagesize(), len)) { 		printf("success\n"); 		free(p); 		return; 	} 	printf("fail\n"); } int main(int argc, char *argv[]) { 	size_t l; 	for (l = 0; l < 4097; l++) 		test(l); 	return 0; }

**Comment by igaw** [comment]
This looks like we have corrupted memory. Let's try to see if valgrind is able to detect the source of the corruption:

`valgrind nvme zns report-zones /dev/nvme1 -n 1 -s 32 -S 15 -o json -d 1`

**Comment by sunxing0210** [comment]
Not cli bug, I find 1st nvme_zns_report_zones len is 64 byte, just for get the number of zones?
The previous question is my ssd return data more than 64 byte.
	
log_len = sizeof(struct nvme_zone_report);
	buff = calloc(1, log_len);
	if (!buff) {
		err = -ENOMEM;
		goto close_fd;
	}

	err = nvme_zns_report_zones(fd, cfg.namespace_id, 0,
				    cfg.state, false, false,
				    log_len, buff,
				    NVME_DEFAULT_IOCTL_TIMEOUT, NULL);
				    
thank you.

**Comment by igaw** [comment]
> Not cli bug, I find 1st nvme_zns_report_zones len is 64 byte, just for get the number of zones?

Yes, the first call is to determine the number of descriptors. In your case, the `-d 1` overwrites this value and limits it the first descriptor.

As I don't have any ZNS drive to test I can't really say what or where things go wrong.  As you have gdb running can you try single step over the `report_zones()` function and figure out what's wrong?

**Comment by sc108-lee** [comment]
Could you try this with #1656?
I haven't got any issues like this
But I found a logical bug from it.

**Comment by igaw** [comment]
No feedback, closing issue.
