### ISSUE TITLE
fguid printed with wrong format

### ISSUE THREAD

**Issue by pierrelabat** [linux-nvme/nvme-cli#1653]
It is a bug.
See the Pull Request below to fix it.
https://github.com/linux-nvme/nvme-cli/pull/1652

The fguid (__u8 fguid[16]) of the Identify Controller Data Structure is made of non printable characters. From the nvme spec "This field uses the EUI-64 based 16-byte designator format". As a result when fguid is not zero, the printf output is garbled/spread on several lines because the format used is a string format (%-.*s).
fguid should be printed the same as other similar fields of the Identify Controller Data Structure (containing 16 non printable characters). So no garbling is occurring.

**Comment by igaw** [comment]
Issues has been fixed. Closing bug report.
