### ISSUE TITLE
Make PDC the default option against targets that are TP 8013/8014 compliant

### ISSUE THREAD

**Issue by martin-gpy** [linux-nvme/nvme-cli#1670]
For targets that are already TP 8013/8014 compliant, the host should consider creating Persistent Discovery Controllers (PDC) as the default during NVMe discovery, instead of the regular short-lived non-PDC.

**Comment by hreinecke** [comment]
... and this should be tied in with the detection of unique discovery subsystems (logging in with the default discovery subsystem NQN, figuring our the unique subsystem NQN, logout, and then re-login persistently with the unique subsystem NQN.)

**Comment by martin-gpy** [comment]
A related ask - while making PDC the default option against a TP 8013/8014 compliant target, care should also be taken to ensure only a single PDC is created for all those records where DUPRETINFO is enabled in the discovery log page data i.e. one need not unnecessarily create PDCs for each record in the discovery log page data if DUPRETINFO is enabled.

**Comment by igaw** [comment]
I've implemented this feature now (#1765). One thing which feels a bit odd is that 'unique discovery controller' means 'persistent discovery controller'. I haven't really figured out how else to say 'make this a  persistent discovery controller'.
