### ISSUE TITLE
Bad JSON when no NVMe detected

### ISSUE THREAD

**Issue by sadziu82** [linux-nvme/nvme-cli#173]
`nvme list --output-format json` doesn't return correct JSON when no NVMe devices are detected. It should be `{}` not an empty output.

```
# nvme list --output-format json
# nvme --version
nvme version 1.2.10.gf075.dirty
```

**Comment by keithbusch** [comment]
Is `{}` the right output or
```
{
  "Devices" : [

  ]
}
```

?

**Comment by keithbusch** [comment]
Eh, just went with `{}`. Fix pushed, thanks for the notification.
