### ISSUE TITLE
"failed nvme_keep_alive_end_io error=10" dmesg error 

### ISSUE THREAD

**Issue by Sheik-Ajith-Ali** [linux-nvme/nvme-cli#1736]
I am getting this error messsage in dmesg in Redhat OS with nvme-cli 2.0 version while running I/O stress test.

Could anyone please let me know why is it occuring/ how to prevent this from occuring.

**Comment by igaw** [comment]
This is the kernel fabrics driver reporting that it's not able to communicate with the controller. Please report this to your distro vendor directly as this is not and upstream bug in nvme-cli.
