### ISSUE TITLE
Negative values when parsing structures with output format JSON

### ISSUE THREAD

**Issue by Neney13rx** [linux-nvme/nvme-cli#1742]
Noticed that with v2+ that nvmecli commands with --output-format=json parses large integers as signed resulting in negative values and converts integers to floating point.

```
# nvme version
nvme version 2.2.1 (git 2.2.1)
libnvme version 1.2 (git 1.2)

# nvme list -o json
{
  "Devices":[
    {
      "NameSpace":1,
      ...
      "UsedBytes":-2147483648,
      "MaximumLBA":937684566,
      "PhysicalSize":-2147483648,
      "SectorSize":4096
    },
```

On another drive, we can observe that calling `id-ctrl` with `--output-format=json` returns floating values for the total and unused capacities entries, in addition to a negative value for the sanicap field.
```
nvme id-ctrl /dev/nvme1 --output-format=json
{
  ...
  "tnvmcap":960197124096.0,
  "unvmcap":0.0,
  ...
  "sanicap":-1610612733,
  ...
```

Normal output displays the correct values.
```
$ sudo nvme id-ctrl /dev/nvme1 --output-format=normal
NVME Identify Controller:
...
tnvmcap   : 960197124096
unvmcap   : 0
...
sanicap   : 0xa0000003
```

**Comment by igaw** [comment]
Fixed by #https://github.com/linux-nvme/nvme-cli/pull/1743
