### ISSUE TITLE
nvme connect command can have many connection with the same backend disk.

### ISSUE THREAD

**Issue by 512868516** [linux-nvme/nvme-cli#176]
[root@nvmf-com ~]# nvme version
nvme version 1.2.18.gc5e4e

[root@nvmf-com ~]# nvme list
Node             SN                   Model                                    Namespace Usage                      Format           FW Rev
/dev/nvme0n1     8a3c8572b23af69e     Linux                                    1           1.07  GB /   1.07  GB    512   B +  0 B   4.8.6-30
[root@nvmf-com ~]# nvme connect -t rdma -a 172.16.130.1 -s 4420 -n nvme1n1
[root@nvmf-com ~]# nvme connect -t rdma -a 172.16.130.1 -s 4420 -n nvme1n1
[root@nvmf-com ~]# nvme list
Node             SN                   Model                                    Namespace Usage                      Format           FW Rev
/dev/nvme0n1     8a3c8572b23af69e     Linux                                    1           1.07  GB /   1.07  GB    512   B +  0 B   4.8.6-30
/dev/nvme1n1     e7d368450dfae3fb     Linux                                    1           1.07  GB /   1.07  GB    512   B +  0 B   4.8.6-30
/dev/nvme2n1     ef26a80c7a8cce5e     Linux                                    1           1.07  GB /   1.07  GB    512   B +  0 B   4.8.6-30
[root@nvmf-com ~]# nvme connect -t rdma -a 172.16.130.1 -s 4420 -n nvme1n1
[root@nvmf-com ~]# nvme list
Node             SN                   Model                                    Namespace Usage                      Format           FW Rev
/dev/nvme0n1     8a3c8572b23af69e     Linux                                    1           1.07  GB /   1.07  GB    512   B +  0 B   4.8.6-30
/dev/nvme1n1     e7d368450dfae3fb     Linux                                    1           1.07  GB /   1.07  GB    512   B +  0 B   4.8.6-30
/dev/nvme2n1     ef26a80c7a8cce5e     Linux                                    1           1.07  GB /   1.07  GB    512   B +  0 B   4.8.6-30
/dev/nvme3n1     dd3ae69372ca5926     Linux                                    1           1.07  GB /   1.07  GB    512   B +  0 B   4.8.6-30

the /dev/nvme0n1 /dev/nvme1n1  /dev/nvme2n1 /dev/nvme3n1 is the same backend disk, on the storage only have one disk.

**Comment by keithbusch** [comment]
I'm pretty sure this is a feature.
