### ISSUE TITLE
make appimage format or binary file

### ISSUE THREAD

**Issue by newyorkthink** [linux-nvme/nvme-cli#1764]
inxi bat or other command , they allow have binary file.

appimage or binary they not use apt-get ,it can run every e:)

**Comment by igaw** [comment]
If I understand your correctly, you are asking us to provide a nvme-cli packaged up as an AppImage,

- https://github.com/AppImageCrafters/appimage-builder
- https://appimage-builder.readthedocs.io/en/latest/hosted-services/github-actions.html

Recently, we had already a quick discussion if we should provide binaries upstream. My response was that I am not willing to spend time on packaging for distributions, so we rather look into how we can provide statically linked binaries.

Though I haven't really thought about AppImage. If it is really just setting up a workflow on github and we are done with it, I am fine to look into.

**Comment by igaw** [comment]
See also #1754

**Comment by igaw** [comment]
We still need to figure out where to upload the result. Currently the image is only available via the artifacts attached to the latest build.

**Comment by newyorkthink** [comment]
I success build :)

**Comment by newyorkthink** [comment]
![Uploading 2023-01-20_18-47_1.png…]()

**Comment by igaw** [comment]
I've experimented with uploading the generated AppImage as release artifact. To get this working the workflow needs to create or update a tag (e.g. tip or latest). This is really ugly and I don't want to allow the workflow actually to do the tags.

That means we need some place for uploading the generated artifact unless we are okay with pointing to the build artifacts. Note these don't have a stable URL...

**Comment by jmhands** [comment]
I see the appimage in the actions, is it possible to upload the appimage for the release builds to make it easy for people to find?

**Comment by igaw** [comment]
We are just missing a place to upload build artifacts.

**Comment by igaw** [comment]
There we go: https://monom.org/linux-nvme/

**Comment by docop** [comment]
Very usefull to have a true portable system and quick check of nvme with this true portable version in appimage. great.
