### ISSUE TITLE
nvme1 did not find a pci resource, open failed No such file or directory while checking effect-logs

### ISSUE THREAD

**Issue by sarabjotsoit** [linux-nvme/nvme-cli#1783]
Steps to recreate:

2. Check the effects-logs using nvmecli 2.1.2

root@dcs:/home/dcs# nvme list 
Node                  Generic               SN                   Model                                    Namespace Usage                      Format           FW Rev  
--------------------- --------------------- -------------------- ---------------------------------------- --------- -------------------------- ---------------- --------
/dev/nvme4n1          /dev/ng4n1            USALP02620QB0003BC   OpenFlex Data24 3200                     1          68.72  GB /  68.72  GB      4 KiB +  0 B   0.9.2399
/dev/nvme2n1          /dev/ng2n1            USALP02620QB0003AC   OpenFlex Data24 3200                     1          68.72  GB /  68.72  GB      4 KiB +  0 B   0.9.2399
/dev/nvme1n1          /dev/ng1n1            A05D3BC8             WUS4BA138DSP3X1                          1           3.84  TB /   3.84  TB      4 KiB +  0 B   R2210801
root@dcs:/home/dcs# nvme effects-log /dev/nvme1
nvme1 did not find a pci resource, open failed No such file or directory

OBSERVATION:

Retested with nvme-cli 1.16. It is working fine.

root@dcs:~# nvme effects-log /dev/nvme1
Admin Command Set
ACS0     [Delete I/O Submission Queue     ] 00000001
ACS1     [Create I/O Submission Queue     ] 00000001
ACS2     [Get Log Page                    ] 00000001
ACS4     [Delete I/O Completion Queue     ] 00000001
ACS5     [Create I/O Completion Queue     ] 00000001
ACS6     [Identify                        ] 00000001
ACS8     [Abort                           ] 00000001
ACS9     [Set Features                    ] 00000001
ACS10    [Get Features                    ] 00000001
ACS12    [Asynchronous Event Request      ] 00000001
ACS13    [Namespace Management            ] 0001001f
ACS16    [Firmware Commit                 ] 0002001d
ACS17    [Firmware Image Download         ] 00000001
ACS20    [Device Self-test                ] 00000001
ACS21    [Namespace Attachment            ] 00010001
ACS29    [NVMEe-MI Send                   ] 00000001
ACS30    [NVMEe-MI Receive                ] 00000001
ACS128   [Format NVM                      ] 0001000f
ACS129   [Security Send                   ] 00000003
ACS130   [Security Receive                ] 00000001
ACS132   [Sanitize                        ] 00000003
ACS198   [Unknown                         ] 00000001
ACS204   [Unknown                         ] 0002001f
ACS209   [Unknown                         ] 00000001
ACS210   [Unknown                         ] 00000001
ACS216   [Unknown                         ] 00000001
ACS217   [Unknown                         ] 00000001
ACS218   [Unknown                         ] 00000001
ACS225   [Unknown                         ] 00000001
ACS226   [Unknown                         ] 00000001
ACS230   [Unknown                         ] 00000001
ACS240   [Unknown                         ] 00000001
ACS241   [Unknown                         ] 00000001
ACS242   [Unknown                         ] 00000001

NVM Command Set
IOCS0    [Flush                           ] 00000001
IOCS1    [Write                           ] 00000003
IOCS2    [Read                            ] 00000001
IOCS4    [Write Uncorrectable             ] 00000003
IOCS8    [Write Zeroes                    ] 00000003
IOCS9    [Dataset Management              ] 00000003
IOCS12   [Verify                          ] 00000001
IOCS13   [Reservation Register            ] 00000001
IOCS14   [Reservation Report              ] 00000001
IOCS17   [Reservation Acquire             ] 00000001
IOCS21   [Reservation Release             ] 00000001

**Comment by igaw** [comment]
The current version of `effect-log` is only expecting PCI devices and not fabric. The version in v1.16 only supported fabric devices. I suppose we should do the same device discovery dance as in `show-registers`.
