### ISSUE TITLE
invalid argument parse from #1790

### ISSUE THREAD

**Issue by sc108-lee** [linux-nvme/nvme-cli#1801]
[root@localhost .build]# ./nvme read /dev/nvme0n1 --data-size=4096
Expected long suffixed integer argument for 'data-size' but got '4096'!

**Comment by igaw** [comment]
`suffix_binary_suffix()` function is used to parse the `--data-size` command line argument. The commit 1e5abd545622 ("util: Update suffix_binary_parse API") introduce this regression. Just a sec.

**Comment by igaw** [comment]
Thanks for the report!
