### ISSUE TITLE
not able to install nvme-cli2.3

### ISSUE THREAD

**Issue by KiranSL** [linux-nvme/nvme-cli#1804]
make install is not working..
![image](https://user-images.githubusercontent.com/85861984/217794305-3bc24da4-b0af-4c06-84e0-c0d5a5874a08.png)

![image](https://user-images.githubusercontent.com/85861984/217794639-4582d214-9d5c-4115-ad98-e12d7b776cef.png)

Requesting provide the help in installing and provide zip file to install in centos

**Comment by igaw** [comment]
We have AppImage for such cases. The only problem they are bit hidden. You find them as build artifcats in the CI runs. The urls are not stable so we can't really point to 'latest'. (will be solved eventually.

But try this here:

https://github.com/linux-nvme/nvme-cli/suites/10876523428/artifacts/548771620

**Comment by KiranSL** [comment]
Hi Daniel,

While instaling this file i am getting

***@***.*** ~]# ./nvme-cli-latest-x86_64.AppImage
/tmp/.mount_nvme-cSoHXVV/usr/sbin/nvme: error while loading shared
libraries: libcrypto.so.3: cannot open shared object file: No such file or
directory

**Comment by igaw** [comment]
Fixed the AppImage build recipe. It includes now libcrypto.so.3  too:

https://github.com/linux-nvme/nvme-cli/suites/10903326839/artifacts/550736621
