### ISSUE TITLE
list-ctrl fails on WD_BLACK SN770 with "invalid field in command" 0x4002

### ISSUE THREAD

**Issue by HughR** [linux-nvme/nvme-cli#1844]
```
$ sudo nvme list
Node                  Generic               SN                   Model                                    Namespace Usage                      Format           FW Rev  
--------------------- --------------------- -------------------- ---------------------------------------- --------- -------------------------- ---------------- --------
/dev/nvme0n1          /dev/ng0n1            224550804922         WD_BLACK SN770 2TB                       1           2.00  TB /   2.00  TB    512   B +  0 B   731100WD

$ sudo nvme list-ctrl /dev/nvme0
NVMe status: Invalid Field in Command: A reserved coded value or an unsupported value in a defined field(0x4002)
```
The OS is Fedora 37, updated a week ago.
The version of nvme-cli is nvme-cli-2.2.1-1.fc37.x86_64

Discussion:

I'm new to nvme-cli so I may be making an obvious mistake.

From issue 411, I infer that this could be related to name-spaces but I don't see that I asked for anything specific to name spaces.  So I guess that list-ctrl decided that name spaces were relevant and then failed when it probed them.

I guess that this is a bug, but it might be in the SN770 firmware or in nvme-cli.

**Comment by igaw** [comment]
Thanks for the feedback @ssusbauer.

So it would work if the firmware supports it.  Sorry, can't really do anything here.
