### ISSUE TITLE
Message of Multiple Update Detected

### ISSUE THREAD

**Issue by metlinux** [linux-nvme/nvme-cli#1866]
I updated my Samsung PM9A1 SSD with this tool, but was wondering about the following output I received while doing so
I got the following messages after executing

```
# nvme fw-download -f GXA7801Q_20221102.bin /dev/nvme0
Firmware download success

# nvme fw-commit -s 2 -a 0 /dev/nvme0
Success committing firmware action:0 slot:2
Multiple Update Detected (MUD) Value: 0
```

I have to wonder about the last line here (Multiple Update Detected), because I believe this functionality is not support on my SSD
I conclude this based upon this outcome of 'nvme id-ctrl -H /dev/nvme0'

```
frmw      : 0x16
  [5:5] : 0     Multiple FW or Boot Update Detection Not Supported
  [4:4] : 0x1   Firmware Activate Without Reset Supported
  [3:1] : 0x3   Number of Firmware Slots
  [0:0] : 0     Firmware Slot 1 Read/Write

```

It states Multiple FW or Boot Update Detection is not Supported

It did make me wonder if I was not having somekind of an error, so it was somewhat confusing.
Would it not make more sense if it is not supported to not use it in the output at all ?

**Comment by igaw** [comment]
The tool will always print the 'MUD status' line because it doesn't test first if it's supported or not. So it's a bit confusing but harmless. Obviously, the `fw-commit` command could be improved to only print the MUD status if it is actually supported.
