### ISSUE TITLE
nvme-cli version 1.9-1 on Ubuntu release focal returns invalid json format 

### ISSUE THREAD

**Issue by bunkar-akamai** [linux-nvme/nvme-cli#1902]
nvme-cli version 1.9-1 with Ubuntu focal release returns empty string as output when asked for JSON and no NVMEs are present on the system.

**Actual Scenario:**

command: nvme list -o json
output: ""  (Empty string)

**Expected Scenario:**
command: nvme list -o json
{

}

**Comment by bunkar-akamai** [comment]
The possible fix for the issue could be as below:

cat patches/nvme-cli-fix.patch 
--- pkgsrc.orig/nvme.c	2023-03-16 10:46:31.157298636 +0100
+++ pkgsrc/nvme.c	2023-03-16 12:20:12.908420032 +0100
@@ -1998,7 +1998,7 @@
 		}
 	}
 
-	if (list_cnt) {
+	if (list_cnt >= 0) {
 		if (fmt == JSON)
 			json_print_list_items(list_items, list_cnt);
 		else

**Comment by ikegami-t** [comment]
The PR #1906 exmaple output is below.
```sh
tokunori@tokunori:~/nvme-cli$ env LANGUAGE=en_US.UTF-8 sudo .build/nvme list --output-format=json
{
  "error":"Failed to scan topology: No such file or directory"
}
```

**Comment by igaw** [comment]
Thanks for the report. @ikegami-t fixed this in upstream (thanks!) .

That said, we are not maintaining the downstream version of nvme-cli in Ubuntu, thus we can't fix it. You need to open a bug report against Ubuntu and the downstream maintainer has to apply a fix.

Anyway, if you want to test it, we build an `AppImage` from the latest version: https://monom.org/linux-nvme/upload/AppImage/nvme-cli-latest-x86_64.AppImage

**Comment by bunkar-akamai** [comment]
> Thanks for the report. @ikegami-t fixed this in upstream (thanks!) .
> 
> That said, we are not maintaining the downstream version of nvme-cli in Ubuntu, thus we can't fix it. You need to open a bug report against Ubuntu and the downstream maintainer has to apply a fix.
> 
> Anyway, if you want to test it, we build an `AppImage` from the latest version: https://monom.org/linux-nvme/upload/AppImage/nvme-cli-latest-x86_64.AppImage

Thanks for the update @igaw
