### ISSUE TITLE
nvme-cli make process is trying to contact github

### ISSUE THREAD

**Issue by pyite** [linux-nvme/nvme-cli#1931]
I am trying to build on a system with no outbound internet access.  This should be possible with the official release zip or tar.gz files, but it is trying to phone home:
...
Cloning into 'libnvme'...
fatal: unable to access 'https://github.com/linux-nvme/libnvme.git/': OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443 

meson.build:48:0: ERROR: Git command failed: ['/usr/bin/git', 'clone', 'https://github.com/linux-nvme/libnvme.git', 'libnvme']

Thanks

**Comment by martin-belanger** [comment]
Hey @pyite 

Have you tried to configure meson with the `--wrap-mode` option? Check [README.md](https://github.com/linux-nvme/nvme-cli/blob/master/README.md) for details.

**Comment by pyite** [comment]
Not yet, but I'll try when I can.  There are a whole ton of dependencies like openssl, sphinx, snowballstemmer, etc that I have to copy over by hand.

**Comment by igaw** [comment]
I recommend not to use the Makefile wrapper, instead use meson directly. The tool knows a lot of options how you can configure your build. I think you want `meson setup --wrap-mode=nodownload .build`. We changed the defaults for the download behavior recently. So the next release should not try to download anymore per default.
