### ISSUE TITLE
When using 'nvme read', output form is different from data and metadata.

### ISSUE THREAD

**Issue by soojung56** [linux-nvme/nvme-cli#1967]
When using 'nvme read', output form is different from data and metadata.
why data output size is 'cfg.data_size'?

cfg.block_count is considered when setting the buffer_size.
but when it is output as the current operation, 'cfg.block_count'  for data is not reflected.

In addition metadata setting output size is mbuffer_size.

- data
`write(dfd, (void *)buffer, cfg.data_size)`
- metadata
` write(mfd, (void *)mbuffer, mbuffer_size)`

**data/metadata setting code in submit_io, nvme.c +7547**
```
buffer_size = ((long long)cfg.block_count + 1) * logical_block_size;
if (cfg.data_size < buffer_size)
    nvme_show_error("Rounding data size to fit block count (%lld bytes)", buffer_size);
else
    buffer_size = cfg.data_size;

/* Get the required block count. Note this is a zeroes based value. */
nblocks = ((buffer_size + (logical_block_size - 1)) / logical_block_size) - 1;

/* Update the data size based on the required block count */
buffer_size = (nblocks + 1) * logical_block_size;

buffer = nvme_alloc(buffer_size, &huge);

...

mbuffer_size = ((unsigned long long)cfg.block_count + 1) * ms;
if (ms && cfg.metadata_size < mbuffer_size)
    nvme_show_error("Rounding metadata size to fit block count (%lld bytes)",
            mbuffer_size);
else
    mbuffer_size = cfg.metadata_size;

mbuffer = malloc(mbuffer_size);
```

**data/metadata output code in submit_io, nvme.c +7668**
```
if (err < 0) {
	nvme_show_error("submit-io: %s", nvme_strerror(errno));
} else if (err) {
	nvme_show_status(err);
} else {
	if (!(opcode & 1) && write(dfd, (void *)buffer, cfg.data_size) < 0) {
		nvme_show_error("write: %s: failed to write buffer to output file",
			strerror(errno));
		err = -EINVAL;
	} else if (!(opcode & 1) && cfg.metadata_size &&
		   write(mfd, (void *)mbuffer, mbuffer_size) < 0) {
		nvme_show_error(
		    "write: %s: failed to write meta-data buffer to output file",
		    strerror(errno));
		err = -EINVAL;
	} else {
		printf("%s: Success\n", command);
	}
}
```

**Comment by igaw** [comment]
Not sure if I understood your question. Is the question about the `args` struct we are preparing and not using `mbuffer_size`? This looks indeed a bit suspicious:

```c
	struct nvme_io_args args = {
		.args_size	= sizeof(args),
		.fd		= dev_fd(dev),
		.nsid		= cfg.namespace_id,
		.slba		= cfg.start_block,
		.nlb		= nblocks,
		.control	= control,
		.dsm		= cfg.dsmgmt,
		.sts		= sts,
		.pif		= pif,
		.dspec		= cfg.dspec,
		.reftag_u64	= cfg.ref_tag,
		.apptag		= cfg.app_tag,
		.appmask	= cfg.app_tag_mask,
		.storage_tag	= cfg.storage_tag,
		.data_len	= buffer_size,
		.data		= buffer,
		.metadata_len	= cfg.metadata_size,   // XXX mbuffer_size?
		.metadata	= mbuffer,
		.timeout	= NVME_DEFAULT_IOCTL_TIMEOUT,
		.result		= NULL,
	};
```

**Comment by soojung56** [comment]
Yes, right. The ultimate issue seems to be the difference in handling data and metadata.

In the case of metadata, the 'cfg.metadata_size' argument is received to set mbuffer_size, and the 'cfg.metadata_size' is passed to the structure. After executing the command, the output size is set to mbuffer_size.

In the case of data, the 'cfg.data_size' argument is received to set buffer_size, and the buffer_size is passed to the structure. However, when setting the output size after executing the command, 'cfg.data_size' is used instead of buffer_size.

**Comment by ikegami-t** [comment]
The implementation part mentioned was added by the change d10feb0.
```c
static int submit_io(int opcode, char *command, const char *desc, int argc, char **argv)
{
...
	struct nvme_io_args args = {
		.data_len	= buffer_size,
...
		.metadata_len	= cfg.metadata_size,
...
```
Also the implementation below was also changed by the comit 68cb097.
```c
	if (err < 0) {
...
	} else {
		if (!(opcode & 1) && write(dfd, (void *)buffer, cfg.data_size) < 0) {
...
		} else if (!(opcode & 1) && cfg.metadata_size &&
			   write(mfd, (void *)mbuffer, mbuffer_size) < 0) {
...
```
As mentioned it seems that it can be fixed to use same `cfg.datasize` / `cfg.metadata_size` or `buffer_size` / `mbuffer_size` values for data and metadata to pass and output.

**Comment by soojung56** [comment]
What I'm trying to say is why you get the buffer size(mbuffer_size) of the metadata and use a different value (cfg.metasize) for the structure.
Also, I wonder why the output for data uses "cfg.data_size" instead of buffer_size for data.


![image](https://github.com/linux-nvme/nvme-cli/assets/69757881/5cce6919-b73f-45e8-8bc4-e0c58936808b)

![image](https://github.com/linux-nvme/nvme-cli/assets/69757881/295871b4-1377-4337-92d0-7ac184965ca8)

Is there anything I'm misunderstanding?
Can you explain to me if there is a specific reason why the code is designed to work this way? If there's anything I don't know, I'd appreciate it if you could let me know about that.

**Comment by igaw** [comment]
> Is there anything I'm misunderstanding?

No, don't think so.  The `cfg.metadata_size` argument was added in 18de3a6d61a7 ("Convert to libnvme") and the change is pretty massive so it is likely just an oversight and wasn't spotted during the review. Let's fix this one.

**Comment by soojung56** [comment]
Thank you very much for your reply. I'll be waiting for the correction.

**Comment by ikegami-t** [comment]
FYI: submit_io related changes commits are below and just fixed pass metadata value by the PR #1970 changes c1abbd7 but still seems the output data and metadata values are not same to use cfg or buffer sizes.
| Commit | Date | Pass | Output | Changes |
--- | --- | --- | --- | ---
| bf5eb4e | Jul 13, 2016 | cfg.block_count | cfg.data_size, cfg.metadata_size | None for pass and output values |
| 2151da2 | Feb 6, 2021 | cfg.block_count | cfg.data_size, cfg.metadata_size | None for pass and output values |
| 68cb097 | Feb 7, 2021 | cfg.block_count | cfg.data_size, ***mbuffer_size*** | Changed output: cfg.metadata_size to mbuffer_size |
| 18de3a6 | Jun 17, 2021 | ***buffer_size***, ***cfg.metadata*** | cfg.data_size, mbuffer_size | Changed pass: cfg.block_count to buffer_size and cfg.metadata_size |
| 0e1edbd | Nov 15, 2021 | buffer_size, cfg.metadata_size | cfg.data_size, mbuffer_size | None for pass and output values |
| 89bddbd | Nov 15, 2021 | buffer_size, cfg.metadata_size | cfg.data_size, mbuffer_size | None for pass and output values |
| b2f2c53 | Nov 18, 2021 | buffer_size, cfg.metadata_size | cfg.data_size, mbuffer_size | None for pass and output values |
| d10feb0 | Jan 11, 2022 | buffer_size, cfg.metadata_size | cfg.data_size, mbuffer_size | None for pass and output values |
| 74c8f79 | Jan 11, 2022 | buffer_size, cfg.metadata_size | cfg.data_size, mbuffer_size | None for pass and output values |
| c1abbd7 | Jun 6, 2023 | buffer_size, ***mbuffer_size*** | cfg.data_size, mbuffer_size | Changed pass: cfg.metadata_size to mbuffer_size |

**Comment by igaw** [comment]
Wow! Nice digging!

So if I understand your table correctly, we also need to update the `cfg.data_size` to `buffer_size` in the output path?

**Comment by soojung56** [comment]
Right. Regarding 'cfg.data_size' in the output, it hasn't been modified to buffer_size!
I checked that the output of the metadata was modified to mbuffer_size.

**Comment by soojung56** [comment]
I think it needs to be modified as shown in the picture below.
![image](https://github.com/linux-nvme/nvme-cli/assets/69757881/3c6d6373-9ccc-4ba7-bc76-01433b419f7f)

**Comment by igaw** [comment]
Makes sense. Let me spin another patch...

**Comment by soojung56** [comment]
@igaw Thank you for your reflection.
