### ISSUE TITLE
Build error.

### ISSUE THREAD

**Issue by seanmaster** [linux-nvme/nvme-cli#200]
Hi,

I update the latest code.
Can not build success, below is error info.
Sounds like need to add linux/types.h in the header.
Please help, thanks.
```
In file included from nvme-print.h:4:0,
                 from nvme-print.c:6:
nvme.h:29:2: error: unknown type name ‘__u8’
  __u8 b[16];
  ^
```

**Comment by keithbusch** [comment]
Okay, thanks for the notice. Installing kernel headers from your package repository will resolve this, but I would rather not have such dependencies in the first place.  Will get back to you on this.

**Comment by keithbusch** [comment]
This should be fixed now. Fix came from Christoph.

**Comment by seanmaster** [comment]
Thanks, I update then can build success.
