### ISSUE TITLE
nvme list: sort entries on output?

### ISSUE THREAD

**Issue by igaw** [linux-nvme/nvme-cli#2001]
The STDOUT output from `nvme list` is not sorted. All entries are printed in the order as the are found in the list. Should we make this a bit more user friendly and sort them?

**Comment by ikegami-t** [comment]
Yes seems better to be sorted by the node name for default as the order was changed as below and also seems it can be added the command option parameter for the sort to change the order.
1.  v1.9: Sorted by the node name.
```
tokunori@tokunori-desktop:~/nvme-cli$ sudo ./nvme list
Node             SN                   ...
---------------- -------------------- ...
/dev/nvme0n1     ...
/dev/nvme1n1     ...
/dev/nvme2n1     ...
```
2.  v2.5: Seems changed as the descending order.
```
tokunori@tokunori-desktop:~/nvme-cli$ sudo .build/nvme list
Node                  Generic               SN                   ...
--------------------- --------------------- -------------------- ...
/dev/nvme2n1          /dev/ng2n1            ...
/dev/nvme1n1          /dev/ng1n1            ...
/dev/nvme0n1          /dev/ng0n1            ...
```
