### ISSUE TITLE
After updating the firmware, "nvme list" does not reflect the new firmware version without rebooting.

### ISSUE THREAD

**Issue by maurizio-lombardi** [linux-nvme/nvme-cli#2007]
After updating nvme firmware, '# nvme list' output does not reflect the new firmware version without rebooting.
However, '# nvme id-ctrl" output does reflect the new version.

The reason is that "nvme list" reads  the stale firmware version from sysfs firmware_rev attribute while "nvme id-ctrl" performes an
nvme identify command.

I see two possible ways to fix this:

1) Modify nvme-cli/libnvme to execute an identify command to get the correct firmware version; problem: in sysfs we will still see the stale version
2) Modify the kernel to execute an identify command before returning the firmware_rev to userspace (I tend to prefer this solution)

Any alternative idea?

**Comment by igaw** [comment]
Duplicated of https://github.com/linux-nvme/nvme-cli/issues/1991
