### ISSUE TITLE
admin-passthru with raw_binary prepends status message

### ISSUE THREAD

**Issue by tkenbo** [linux-nvme/nvme-cli#2025]
https://github.com/linux-nvme/nvme-cli/commit/414f1eda0bb7540c58cbb1f85dee6c6d84abba43#commitcomment-122245811

Per discussion in this update, currently status message of admin-passthru command is written to stdout and prepended to the data returned from the device if -i option is not used.  I'd like to request separating status message from stdout like it used to be if possible.

**Comment by ikegami-t** [comment]
Just confirmed the commit e5b3c2f to change stdout to stderr before. So I will fix this as revert.
