### ISSUE TITLE
Error message when arguments are correct

### ISSUE THREAD

**Issue by vinotion** [linux-nvme/nvme-cli#2030]
When using `nvme` in a boot script, the following error intermittently occurred, however the argument was correct:

`Expected byte argument for 'sanact' but got '4'!`

For version 1.13, we traced it back to `errno` not being initialized to zero before calling `strtoul` in `util/argconfig.c`. Maybe this bug is still in master.

**Comment by igaw** [comment]
Yep, the argparser is still very similar to the 1.13 version and doesn't explicitly set `errno` to 0 before calling `strto*`.
We should do this, the man page example does this as well.
