### ISSUE TITLE
doesn't compile (ubuntu) last commit 0eda7a67c106e94f682101f2724136df206d8009 

### ISSUE THREAD

**Issue by moshe-y** [linux-nvme/nvme-cli#2032]
meson compile -C .build
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /usr/local/bin/ninja -C /githubVersion/nvme-cli/.build
ninja: Entering directory `githubVersion/nvme-cli/.build'
[53/89] Compiling C object nvme.p/nvme-print-json.c.o
../nvme-print-json.c: In function 'json_print_nvme_subsystem_list':
../nvme-print-json.c:1804:54: warning: implicit declaration of function 'nvme_subsystem_get_iopolicy'; did you mean 'nvme_subsystem_get_type'? [-Wimplicit-function-declaration]
 1804 |                                                      nvme_subsystem_get_iopolicy(s));
      |                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                      nvme_subsystem_get_type
../nvme-print-json.c:1804:54: warning: passing argument 3 of 'json_object_add_value_string' makes pointer from integer without a cast [-Wint-conversion]
 1804 |                                                      nvme_subsystem_get_iopolicy(s));
      |                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                      |
      |                                                      int
In file included from ../nvme.h:30,
                 from ../nvme-print.h:5,
                 from ../nvme-print-json.c:6:
../util/json.h:31:98: note: expected 'const char *' but argument is of type 'int'
   31 | static inline int json_object_add_value_string(struct json_object *o, const char *k, const char *v) {
      |                                                                                      ~~~~~~~~~~~~^
../nvme-print-json.c: In function 'json_simple_topology':
../nvme-print-json.c:2766:54: warning: passing argument 3 of 'json_object_add_value_string' makes pointer from integer without a cast [-Wint-conversion]
 2766 |                                                      nvme_subsystem_get_iopolicy(s));
      |                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                      |
      |                                                      int
In file included from ../nvme.h:30,
                 from ../nvme-print.h:5,
                 from ../nvme-print-json.c:6:
../util/json.h:31:98: note: expected 'const char *' but argument is of type 'int'
   31 | static inline int json_object_add_value_string(struct json_object *o, const char *k, const char *v) {
      |                                                                                      ~~~~~~~~~~~~^
[86/89] Compiling C object nvme.p/nvme-print-stdout.c.o
../nvme-print-stdout.c: In function 'stdout_subsystem':
../nvme-print-stdout.c:984:32: warning: implicit declaration of function 'nvme_subsystem_get_iopolicy'; did you mean 'nvme_subsystem_get_type'? [-Wimplicit-function-declaration]
  984 |                                nvme_subsystem_get_iopolicy(s));
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                nvme_subsystem_get_type
../nvme-print-stdout.c:983:49: warning: format '%s' expects argument of type 'char *', but argument 4 has type 'int' [-Wformat=]
  983 |                         printf("%*s   iopolicy=%s\n", len, " ",
      |                                                ~^
      |                                                 |
      |                                                 char *
      |                                                %d
  984 |                                nvme_subsystem_get_iopolicy(s));
      |                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                |
      |                                int
../nvme-print-stdout.c: In function 'stdout_simple_topology':
../nvme-print-stdout.c:4864:49: warning: format '%s' expects argument of type 'char *', but argument 4 has type 'int' [-Wformat=]
 4864 |                         printf("%*s   iopolicy=%s\n", len, " ",
      |                                                ~^
      |                                                 |
      |                                                 char *
      |                                                %d
 4865 |                                nvme_subsystem_get_iopolicy(s));
      |                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                |
      |                                int
[89/89] Linking target nvme
FAILED: nvme 
cc  -o nvme nvme.p/nbft.c.o nvme.p/fabrics.c.o nvme.p/nvme.c.o nvme.p/nvme-models.c.o nvme.p/nvme-print.c.o nvme.p/nvme-print-stdout.c.o nvme.p/nvme-print-binary.c.o nvme.p/nvme-rpmb.c.o nvme.p/nvme-wrap.c.o nvme.p/plugin.c.o nvme.p/libnvme-wrap.c.o nvme.p/nvme-print-json.c.o nvme.p/ccan_ccan_hash_hash.c.o nvme.p/ccan_ccan_htable_htable.c.o nvme.p/ccan_ccan_ilog_ilog.c.o nvme.p/ccan_ccan_likely_likely.c.o nvme.p/ccan_ccan_list_list.c.o nvme.p/ccan_ccan_str_debug.c.o nvme.p/ccan_ccan_str_str.c.o nvme.p/ccan_ccan_strset_strset.c.o nvme.p/plugins_amzn_amzn-nvme.c.o nvme.p/plugins_dell_dell-nvme.c.o nvme.p/plugins_dera_dera-nvme.c.o nvme.p/plugins_fdp_fdp.c.o nvme.p/plugins_huawei_huawei-nvme.c.o nvme.p/plugins_innogrit_innogrit-nvme.c.o nvme.p/plugins_inspur_inspur-nvme.c.o nvme.p/plugins_intel_intel-nvme.c.o nvme.p/plugins_memblaze_memblaze-nvme.c.o nvme.p/plugins_micron_micron-nvme.c.o nvme.p/plugins_nbft_nbft-plugin.c.o nvme.p/plugins_netapp_netapp-nvme.c.o nvme.p/plugins_nvidia_nvidia-nvme.c.o nvme.p/plugins_scaleflux_sfx-nvme.c.o nvme.p/plugins_seagate_seagate-nvme.c.o nvme.p/plugins_shannon_shannon-nvme.c.o nvme.p/plugins_solidigm_solidigm-nvme.c.o nvme.p/plugins_toshiba_toshiba-nvme.c.o nvme.p/plugins_transcend_transcend-nvme.c.o nvme.p/plugins_virtium_virtium-nvme.c.o nvme.p/plugins_wdc_wdc-nvme.c.o nvme.p/plugins_wdc_wdc-utils.c.o nvme.p/plugins_ymtc_ymtc-nvme.c.o nvme.p/plugins_zns_zns.c.o nvme.p/plugins_solidigm_solidigm-id-ctrl.c.o nvme.p/plugins_solidigm_solidigm-util.c.o nvme.p/plugins_solidigm_solidigm-smart.c.o nvme.p/plugins_solidigm_solidigm-garbage-collection.c.o nvme.p/plugins_solidigm_solidigm-latency-tracking.c.o nvme.p/plugins_solidigm_solidigm-log-page-dir.c.o nvme.p/plugins_solidigm_solidigm-telemetry.c.o nvme.p/plugins_solidigm_solidigm-internal-logs.c.o nvme.p/plugins_solidigm_solidigm-market-log.c.o nvme.p/plugins_solidigm_solidigm-telemetry_cod.c.o nvme.p/plugins_solidigm_solidigm-telemetry_header.c.o nvme.p/plugins_solidigm_solidigm-telemetry_config.c.o nvme.p/plugins_solidigm_solidigm-telemetry_data-area.c.o nvme.p/plugins_solidigm_solidigm-telemetry_nlog.c.o nvme.p/plugins_ocp_ocp-utils.c.o nvme.p/plugins_ocp_ocp-nvme.c.o nvme.p/plugins_ocp_ocp-clear-fw-update-history.c.o nvme.p/plugins_ocp_ocp-smart-extended-log.c.o nvme.p/plugins_ocp_ocp-fw-activation-history.c.o nvme.p/util_argconfig.c.o nvme.p/util_base64.c.o nvme.p/util_cleanup.c.o nvme.p/util_crc32.c.o nvme.p/util_suffix.c.o nvme.p/util_types.c.o nvme.p/util_json.c.o -Wl,--as-needed -Wl,--no-undefined -Wl,-rpath,/usr/local/lib/x86_64-linux-gnu -Wl,-rpath-link,/usr/local/lib/x86_64-linux-gnu -Wl,--start-group -ldl /usr/local/lib/x86_64-linux-gnu/libnvme.so /usr/local/lib/x86_64-linux-gnu/libnvme-mi.so /usr/lib/x86_64-linux-gnu/libjson-c.so -Wl,--end-group
/usr/bin/ld: nvme.p/nvme-print-stdout.c.o: in function `stdout_subsystem':
/githubVersion/nvme-cli/.build/../nvme-print-stdout.c:983: undefined reference to `nvme_subsystem_get_iopolicy'
/usr/bin/ld: nvme.p/nvme-print-stdout.c.o: in function `stdout_simple_topology':
/githubVersion/nvme-cli/.build/../nvme-print-stdout.c:4864: undefined reference to `nvme_subsystem_get_iopolicy'
/usr/bin/ld: nvme.p/nvme-print-json.c.o: in function `json_print_nvme_subsystem_list':
/githubVersion/nvme-cli/.build/../nvme-print-json.c:1804: undefined reference to `nvme_subsystem_get_iopolicy'
/usr/bin/ld: nvme.p/nvme-print-json.c.o: in function `json_simple_topology':
/githubVersion/nvme-cli/.build/../nvme-print-json.c:2766: undefined reference to `nvme_subsystem_get_iopolicy'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**Comment by martin-belanger** [comment]
Hey @moshe-y - Just FYI. If `libnvme` is being built as a subproject of `nvme-cli` (I believe that `meson` does that by default when `libnvme` is not installed separately), you sometimes need to update the subproject repo with `meson subprojects update` to keep it up to date with upstream.
