### ISSUE TITLE
nvme-cli recipes file(.bb)

### ISSUE THREAD

**Issue by banklpjhgb** [linux-nvme/nvme-cli#2037]
where can I find the .bb file of nvme-cli2.0, I use yocto. thank you

**Comment by igaw** [comment]
http://cgit.openembedded.org/meta-openembedded/tree/meta-oe/recipes-bsp/nvme-cli/nvme-cli_2.5.bb

Be aware the recipe has a bug. The `hostnqn` and `hostid` should match which is not the case here:

```
pkg_postinst_ontarget:${PN}() {
    ${sbindir}/nvme gen-hostnqn > ${sysconfdir}/nvme/hostnqn
    ${bindir}/uuidgen > ${sysconfdir}/nvme/hostid
}
```
The `uuidgen` call is wrong, the hostid should be derived from `hostnqn`
