### ISSUE TITLE
Unable to find the parameters queue id and connect attribute in nvme connect command in host

### ISSUE THREAD

**Issue by ksubbiahx** [linux-nvme/nvme-cli#204]
Hi,

 queue id and connect attribute options are not available in nvme connect command in host.

**Comment by hreinecke** [comment]
The 'connect' command to nvme-cli is _not_ just issuing the command itself, but it also establishes the association first (which is protocol specific). Which means we're not just formatting a pass-through command but rather perform a complex operation here.

Why do you need the 'queue id', anyway? Are you trying to connect individual I/O queues?

**Comment by hreinecke** [comment]
Closing.
