### ISSUE TITLE
Why can’t I find the KV command set in the nvme-cli-v2.5?

### ISSUE THREAD

**Issue by cljglll** [linux-nvme/nvme-cli#2053]
Is it not supported?

**Comment by keithbusch** [comment]
No one contributed it. I am not aware of anyone who even has access to a production level implementation, but if someone does and wants to develop the '`kv`' command set extension, sounds good; key-value is an NVMe TWG supported command set, so it's welcome here even if it was a bad idea.

Linux kernel exports generic namespaces (ex, /dev/ng0n1), so driver kv support is in place to handle commands via the low level "`nvme io-passthru`' command, but a '`kv`' extension would certainly be more user friendly.

**Comment by cljglll** [comment]
> No one contributed it. I am not aware of anyone who even has access to a production level implementation, but if someone does and wants to develop the '`kv`' command set extension, sounds good; key-value is an NVMe TWG supported command set, so it's welcome here even if it was a bad idea.
> 
> Linux kernel exports generic namespaces (ex, /dev/ng0n1), so driver kv support is in place to handle commands via the low level '`nvme io-passthru`' command, but a '`kv`' extension would certainly be more user friendly.

So it is privately owned by the manufacturer of SSD. Thank you for your reply.
