### ISSUE TITLE
How to make NS Management and Attachment  Supported Create-ns ?

### ISSUE THREAD

**Issue by wuwenjuncool** [linux-nvme/nvme-cli#209]
I Use intel P3700 SSD and I  Use the nvme-cli "create-ns" command to create a namespace,However it seem my NS Management and Attachment Not Supported it. Is there any way to support it? 
My Controller info:
**NVME Identify Controller:
vid     : 0x8086
ssvid   : 0x8086
sn      : PHFT6054007P1P6JGN
mn      : INTEL SSDPE2MD016T4
fr      : 8DV101H0
rab     : 0
ieee    : 5cd2e4
cmic    : 0
mdts    : 5
cntlid  : 0
ver     : 0
rtd3r   : 0
rtd3e   : 0
oaes    : 0
ctratt  : 0
oacs    : 0x6
acl     : 3
aerl    : 3
frmw    : 0x2
lpa     : 0x2
elpe    : 63
npss    : 0
avscc   : 0
apsta   : 0
wctemp  : 0
cctemp  : 0
mtfa    : 0
hmpre   : 0
hmmin   : 0
tnvmcap : 0
unvmcap : 0
rpmbs   : 0
edstt   : 0
dsto    : 0
fwug    : 0
kas     : 0
hctma   : 0
mntmt   : 0
mxtmt   : 0
sanicap : 0
sqes    : 0x66
cqes    : 0x44
maxcmd  : 0
nn      : 1
oncs    : 0x6
fuses   : 0
fna     : 0x7
vwc     : 0
awun    : 0
awupf   : 0
nvscc   : 0
acwu    : 0
sgls    : 0
subnqn  :
ioccsz  : 0
iorcsz  : 0
icdoff  : 0
ctrattr : 0
msdbd   : 0
ps    0 : mp:25.00W operational enlat:0 exlat:0 rrt:0 rrl:0
          rwt:0 rwl:0 idle_power:- active_power:-
**
nvme id-ctrl /dev/nvme0n1 -H | grep "NS Management"
 [3:3] : 0     NS Management and Attachment Not Supported

**Comment by keithbusch** [comment]
That device does not support namespace management. That command wasn't added until the 1.2 version of the specification, and the device you have is a 1.0 compatible.
