### ISSUE TITLE
apptag and appmask inverted

### ISSUE THREAD

**Issue by AndrewMeir** [linux-nvme/nvme-cli#212]
apptag and appmask seem to be inverted during the handover to ioctl:
`int nvme_io(int fd, __u8 opcode, __u64 slba, __u16 nblocks, __u16 control,

	    __u32 dsmgmt, __u32 reftag, __u16 apptag, __u16 appmask, void *data,

	    void *metadata) {
	struct nvme_user_io io = {
(snip)

		.appmask	= apptag,

		.apptag		= appmask,

`

**Comment by keithbusch** [comment]
Indeed, thanks for the notice. Will get a fix in shortly.

**Comment by keithbusch** [comment]
Fix pushed.

**Comment by AndrewMeir** [comment]
Very speedy response - thanks Keith!
