### ISSUE TITLE
Auth hostkey not being read from conf file as mentioned in docs

### ISSUE THREAD

**Issue by shiftee** [linux-nvme/nvme-cli#2120]
The following line mentions that a secret will be read from a configuration file if not specified on command line:
https://github.com/linux-nvme/nvme-cli/blob/f3adfa69eb6afab2f827bed03ab2de2cd0824964/Documentation/nvme-connect.txt#L111

I don't think this is true.

Libnvme has code for reading the hostnqn and hostid, but nothing for the secret/hostkey as far as I can see:
https://github.com/linux-nvme/libnvme/blob/2d631eab088c642aff986e5eaa84a996b48baf5e/src/nvme/fabrics.c#L1416

Should the code be added, or the documentation removed?

**Comment by igaw** [comment]
The initial idea and implementation was to store the key under `/etc/nvme`. But security aware folks pointed out that this is not a good idea. Thus we are not storing the key in this file anymore. `gen-dhchap` just prints the secret on `stdout` and stores into the kernel keyring. 

We should remove this part in the documentation.
