### ISSUE TITLE
app-tag-mask param too narrow

### ISSUE THREAD

**Issue by AndrewMeir** [linux-nvme/nvme-cli#213]
The app-tag-mask param should be 16 bits. The iotcl layer has 16 bit width for this param but the front-end extraction in submit_io() is constrained to byte-width:
`	struct config {`
`(snip)`
`		__u8  app_tag_mask;`

and
`	const struct argconfig_commandline_options command_line_options[] = {`
`(snip)`
`		{"app-tag-mask",      'm', "NUM",  CFG_BYTE,        &cfg.app_tag_mask,      required_argument, app_tag_mask},`

**Comment by keithbusch** [comment]
Yep, thanks for the notice. Fix pushed.
