### ISSUE TITLE
show `host-iface` and `host-traddr` in `list-subsys` and `show-topology`

### ISSUE THREAD

**Issue by igaw** [linux-nvme/nvme-cli#2137]
I am getting bug reports where it is not clear which `host-iface` and/or `host-traddr` has been used. Let's add them to `list-subsys` and `show-topology` which should help in future to debug such setups a bit quicker.

**Comment by martin-belanger** [comment]
Note that the kernel also reports the socket's source address (`src_addr=`) in the controller's `address` attribute (TCP only). 

For the case where `host-iface` and `host-traddr` are not provided by the user (and therefore the kernel automatically selects the interface and source-address), `src-addr=` is the only way to tell on which interface a connection is made and which source address is associated with that connection.
