### ISSUE TITLE
Update get_log message for non-dw aligned error

### ISSUE THREAD

**Issue by Neney13rx** [linux-nvme/nvme-cli#2146]
The get_log command is enforcing DWORD alignment in the data length but the error message says "non-dw aligned required" which is confusing.

https://github.com/linux-nvme/nvme-cli/blob/7799dfd9f13953c7f03c565bdb22bfbe94db7ec3/nvme.c#L2250

**Comment by igaw** [comment]
`nvme_get_log` function in libnvme will round down the length. Let's say an user ask for 17  bytes, only get 16 bytes will requested. We cut it short. I think this is the reason why we have this check there and an proper error message. 

Don't know if it would be clever to round up and request more and  then trim the result on our end. That might not work.

My take is that it makes sense to enforce valid command line arguments.
