### ISSUE TITLE
Removing unactivated firmware from slot

### ISSUE THREAD

**Issue by obswwf** [linux-nvme/nvme-cli#2170]
After running `nvme fw-commit -s 2 -a 0 /dev/nvme0` and `nvme fw-log /dev/nvme0` I realized that the new firmware version is identical to the old one in `frs1`. Running `nvme reset /dev/nvme0` has no effect. Is there a way to remove the new firmware from `frs2`?

**Comment by ikegami-t** [comment]
Seems needed to replace the frs2 firmware with the new version firmware if you have instead of the removing since seems not able to just remove the frs2 firmware.

**Comment by keithbusch** [comment]
There is no commit action to evict an image from a slot. You have to overwrite it with something else.

**Comment by obswwf** [comment]
Are there plans to implement this feature in a future release?

**Comment by ikegami-t** [comment]
As far as confirmed NVMe TPs and OCP specification seems no plan for the feature.

**Comment by igaw** [comment]
If the nvme committee defines this feature we can implement it. Until then, nothing we can do. So you need to talk to them first.
