### ISSUE TITLE
id-ctrl shows odd characters from tnvmcap

### ISSUE THREAD

**Issue by Ondjultomte** [linux-nvme/nvme-cli#2194]
odd characters
<img width="634" alt="image" src="https://github.com/linux-nvme/nvme-cli/assets/16661547/83766bc9-61a0-493e-b800-9aa3ba293389">

<img width="607" alt="image" src="https://github.com/linux-nvme/nvme-cli/assets/16661547/307350bb-6256-4555-8fb8-c882dcf3382c">

same odd characeters from the other drive

<img width="607" alt="image" src="https://github.com/linux-nvme/nvme-cli/assets/16661547/661a9b8b-a891-452f-b386-80e46142d265">

**Comment by martin-belanger** [comment]
I believe this issue was already reported and addressed by: https://github.com/linux-nvme/nvme-cli/issues/2061
