### ISSUE TITLE
Consider disable NBFT when ACPI is not present

### ISSUE THREAD

**Issue by felixonmars** [linux-nvme/nvme-cli#2198]
On my riscv64 devices, the path /sys/firmware/acpi/tables doesn't exist so that `nvme connect-all` fails with:

```
Failed to open /sys/firmware/acpi/tables.
```

This renders the provided systemd services hard to use because I can't seem to pass `--no-nbft` in the config file.

Would it be a good idea to disable NBFT automatically when it's not available?

**Comment by igaw** [comment]
Absolutely, we should just ignore it silently
