### ISSUE TITLE
Fix code scanning alert - Comparison of narrow type with wide type in loop condition

### ISSUE THREAD

**Issue by igaw** [linux-nvme/nvme-cli#2204]
[
plugins/wdc/wdc-nvme.c:9761](https://github.com/linux-nvme/nvme-cli/blob/79abafe689432647b97a441b34714ab2b2708d4d/plugins/wdc/wdc-nvme.c#L9761-L9761)

Tracking issue for:
- [ ] https://github.com/linux-nvme/nvme-cli/security/code-scanning/2

**Comment by ikegami-t** [comment]
Let us close the issue since the changes merged.
