### ISSUE TITLE
Fix code scanning alert - Time-of-check time-of-use filesystem race condition

### ISSUE THREAD

**Issue by igaw** [linux-nvme/nvme-cli#2205]
https://github.com/linux-nvme/nvme-cli/blob/79abafe689432647b97a441b34714ab2b2708d4d/plugins/micron/micron-nvme.c#L332-L332

Often it is necessary to check the state of a file before using it. These checks usually take a file name to be checked, and if the check returns positively, then the file is opened or otherwise operated upon.

Tracking issue for:
- [ ] https://github.com/linux-nvme/nvme-cli/security/code-scanning/4

**Comment by ikegami-t** [comment]
This issue also can be closed.
