### ISSUE TITLE
Supported Log Pages crashed when using json output

### ISSUE THREAD

**Issue by yalanliufio** [linux-nvme/nvme-cli#2213]
This is the output of supported log page:

nvme supported-log-pages /dev/nvme3 -o json
nvme: ../subprojects/json-c-0.16/json_object.c:1479: json_object_array_add: Assertion `json_object_get_type(jso) == json_type_array' failed.
Aborted (core dumped)

This is the nvme version I am using:
nvme --version
nvme version 2.2.1 (git 2.2.1+)
libnvme version 1.2 (git 1.2)

**Comment by igaw** [comment]
Thanks for the report.
