### ISSUE TITLE
nvme wdc cap-diag /dev/nvme0 - Decode

### ISSUE THREAD

**Issue by dastasho** [linux-nvme/nvme-cli#2221]
Hello everyone, I wanted to check if there is a way to decode the file that is gathered through the command

`nvme wdc cap-diag /dev/nvme0`

It generates a ".bin" file and opening it, gives a part human readable information and part gibberish, which I suspect it is either encrypted or requires some sort of the tool to read it.

**Comment by igaw** [comment]
As this a plugin maintained by WDC I can't really say much about this command. Maybe @jeff-lien-wdc knows more?

**Comment by jeff-lien-wdc** [comment]
@dastasho The cap-diag bin file contains proprietary debug data.  We do have internal tools that can be used to decode the file but we don't release them to the public.

**Comment by dastasho** [comment]
Thank you for the responses!
