### ISSUE TITLE
nvme create-ns fails on 32-bit systems if nsize is large

### ISSUE THREAD

**Issue by vimmanuel** [linux-nvme/nvme-cli#231]
On 32-bit systems nvme create-ns returns the following error:
> nvme create-ns /dev/nvme0 -s 0xba4d4ab0 -c 0xba4d4ab0 -f 0
Expected long suffixed integer argument for 'nsze' but got '0xba4d4ab0'!

Using strtoll instead of strtol fixed the problem. In suffix.c, suffix_binary_parse(), around line 116,
long long ret = strtoll(value, &suffix, 0);

**Comment by keithbusch** [comment]
Thanks for the notice. Should be fixed now.
