### ISSUE TITLE
nvme get-property/set-property shows Invalid Command Opcode (0x6001)

### ISSUE THREAD

**Issue by vinjin-lo-wdc** [linux-nvme/nvme-cli#2318]
Hi,

I am currently facing issue when i tried to set-property/get-property on my NVMe driver. 
![image](https://github.com/linux-nvme/nvme-cli/assets/131999451/80b39c23-258b-4772-92d9-e94354a5da06)

The nvme version that I'm using:
![image](https://github.com/linux-nvme/nvme-cli/assets/131999451/a13383b2-cd92-4ce8-9331-3f8affc430db)

However, the function show-regs works fine on 2.8.
![image](https://github.com/linux-nvme/nvme-cli/assets/131999451/16da0a60-d4bb-45cc-a7d1-10b849206f48)

I also ensure that `io_memory=relaxed` on I/O Memory Configuration
![image](https://github.com/linux-nvme/nvme-cli/assets/131999451/f796b098-bb66-4082-9aa8-c1dfff7071d1)

NVME Error log:
[nvme_error_log.txt](https://github.com/linux-nvme/nvme-cli/files/15135334/nvme_error_log.txt)

**Comment by keithbusch** [comment]
The "get-property" command only works for nvme-over-fabrics targets. PCIe doesn't need it because the properties are memory mapped.
