### ISSUE TITLE
Add support for Directives in NVM Write command

### ISSUE THREAD

**Issue by visheshvijay** [linux-nvme/nvme-cli#235]
According to NVMe 1.3 spec 

In DWORD12 of NVM write command, DTYPE field is there 20th to 23rd bit
Please add it in NVMe cli

Thanks,
Vishesh

**Comment by keithbusch** [comment]
Commit for directive type and directive specific pushed to master.

https://github.com/linux-nvme/nvme-cli/commit/66361e44c8adb5a39b09a8c4c11556f65ac0bde5

**Comment by visheshvijay** [comment]
thanks
