### ISSUE TITLE
Can there be nvme --disconnect-all

### ISSUE THREAD

**Issue by pareshpp** [linux-nvme/nvme-cli#236]
Just as we have connect-all, can there be disconnect-all..

# nvme  | grep connect
The '<device>' may be either an NVMe character device (ex: /dev/nvme0) or an
nvme block device (ex: /dev/nvme0n1).  
connect-all     Discover and Connect to NVMeoF subsystems
  connect         Connect to NVMeoF subsystem
  disconnect      Disconnect from NVMeoF subsystem
# nvme --version
nvme version 1.0

**Comment by keithbusch** [comment]
I think this would be fine. i'm not as familiar with the fabrics as the pci side, though, so might be some time before i can get around to this.

**Comment by hreinecke** [comment]
Has been implemented. Closing.
