### ISSUE TITLE
How do I make nvme-cli work to a /dev/sda device?

### ISSUE THREAD

**Issue by jcdutton** [linux-nvme/nvme-cli#2385]
How do I make nvme-cli work to a /dev/sda device?

I have a nvme device in a usb enclosure.
I can use smarctl to speak to the nvme device.
I would like the "nvme" command from nvme-cli to also be able to talk to it.

**Comment by keithbusch** [comment]
nvmecli uses ioctls provided by the Kernel's NVMe layer to send commands. Devices that present themselves through the scsi layer can't be used by this program.
