### ISSUE TITLE
Core dump observed with nvme cli

### ISSUE THREAD

**Issue by visheshvijay** [linux-nvme/nvme-cli#242]
Hi Keith,

My environment is
RHEL 7.3
nvme cli 1.4 release
name space - 4K format

[root@jaguar54 home]# nvme read /dev/nvme0n1 -s 0 -c 9999 -z 40960000 -d data
read: Success
[root@jaguar54 home]# nvme compare /dev/nvme0n1 -s 0 -c 999 -z 4096000 -d data
Segmentation fault (core dumped)

Let me know if you need anything

Thanks,
Vishesh

**Comment by hreinecke** [comment]
Outdated issue. Closing.
