### ISSUE TITLE
NVMe Command Get Feature Fid=0x8 Aggregation Time unit should be us, rather than ms

### ISSUE THREAD

**Issue by shmily1012** [linux-nvme/nvme-cli#246]
NVMe Command Get Feature Fid=0x8 Aggregation Time unit should be us, rather than ms.
![image](https://user-images.githubusercontent.com/22685791/34633161-25b2b602-f22f-11e7-9285-045c78747754.png)

**Comment by keithbusch** [comment]
Thanks, fix pushed.
