### ISSUE TITLE
nvme-cli:2.10.2: LIBNVME_MI_ and LIBNVME_1.10 not found error seen with Ubuntu 24.04 (Kernel 6.8.0-31)

### ISSUE THREAD

**Issue by sarabjotsoit** [linux-nvme/nvme-cli#2472]
nvme: /lib/x86_64-linux-gnu/libnvme-mi.so.1: version `LIBNVME_MI_1_10' not found (required by nvme)
nvme: /lib/x86_64-linux-gnu/libnvme.so.1: version `LIBNVME_1.10' not found (required by nvme)
nvme: /lib/x86_64-linux-gnu/libnvme.so.1: version `LIBNVME_1.9' not found (required by nvme)

**Comment by igaw** [comment]
This sounds like you are running a newly build nvme-cli against an older libnvme. How did you build install nvme-cli?  Please share your exact command line.

**Comment by sarabjotsoit** [comment]
Hi, @igaw 

I just tried make and make install on top of Ubuntu 24.04.

**Comment by igaw** [comment]
I suppose it fixed the problem. I close the issue now.
