### ISSUE TITLE
ocp uuidx

### ISSUE THREAD

**Issue by YUEyuan310** [linux-nvme/nvme-cli#2582]
Why do some OCP commands specify UUID, while others do not？

ocp_get_uuid_index(dev, &uuid_index);？

For example：
The command fw activate history specifies uuidx
The command hardware-component-log doesn't specify uuidx.

**Comment by YUEyuan310** [comment]
Should the uuid function be completed?

**Comment by ikegami-t** [comment]
Because it is required by the OCP specification. For example the error injection set features required it as below by the OCP version 2.6.
![ocp-error-inject-set](https://github.com/user-attachments/assets/7727bcf3-0480-4d5c-88d3-98a0105e90d5)
But it was not required by the OCP version 1.0.3 as below.
![ocp-error-inject-set-v1 0 3](https://github.com/user-attachments/assets/11f368a7-de2d-4be2-bc75-1a477580303a)

**Comment by YUEyuan310** [comment]
> Sorry the answer above was not correct. The UUID is described by the set features commands but as @YUEyuan310 mentioned it is required for the get log page command also as below so needed to fix OCP get log page commands not set the uuid index to use it. ![uuid](https://private-user-images.githubusercontent.com/44117581/388579344-034e7faf-85ed-44c5-8b6d-b96eb4bc7fd8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNDAyNDQsIm5iZiI6MTczMjIzOTk0NCwicGF0aCI6Ii80NDExNzU4MS8zODg1NzkzNDQtMDM0ZTdmYWYtODVlZC00NGM1LThiNmQtYjk2ZWI0YmM3ZmQ4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDAxNDU0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2ZDZhYzczZGM4YTU1ZGRmOWM2MDAzODdhYzMxZjhkYTBhZDU0YWE5ZmZhMmNlNmI5ODBmZmFiZTRiM2NhMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CyhS5_MrovT7kANt-F6yyr7bSf4TyqapLY2IpZxYGJ8)

I share your opinion that the get-log command in OCP needs to have its uuidx functionality completed.

**Comment by sc108-lee** [comment]
Yes I agree, we should add into the OCP get log commands.

**Comment by igaw** [comment]
I've merged the PRs. Thanks everyone!
