### ISSUE TITLE
`scripts/build.sh -m muon` fails on CentOS8, 9 and debian

### ISSUE THREAD

**Issue by igaw** [linux-nvme/nvme-cli#2590]
Hello everyone, I encountered this issue while compiling a new version recently. I have tried CentOS 8, 9, and debian10, but they all have this problem. Do you have any good solutions? thank you

# scripts/build.sh -m muon

/opt/nvme-cli/.build-tools/muon /opt/nvme-cli
+ dir=stage1
+ mkdir -p stage1
+ pkgconf_cmd=
+ '[' '' = no-pkgconf ']'
+ command -v pkgconf
+ pkgconf_cmd=pkgconf
+ '[' -n pkgconf ']'
+ pkgconf libpkgconf
+ pkgconf_cflags=
+ pkgconf_libs=
+ gcc -std=c99 -Iinclude src/amalgam.c -o stage1/muon-bootstrap
err invalid option: '_bestline=disabled_'

_Originally posted by @admin-cmd-shell in https://github.com/linux-nvme/nvme-cli/issues/2108#issuecomment-2507364346_

**Comment by admin-cmd-shell** [comment]
您好！您的邮件已收到！我查阅后，尽快回复您！          如有急事请致电：17690573035                                                   ——张超杰
