### ISSUE TITLE
any examples on using security send /security recevie command using nvme cli

### ISSUE THREAD

**Issue by vamseekrishna25** [linux-nvme/nvme-cli#2613]
the current documentation on these commands is very vague not even an example on using these commands for basic security operation like Level 0 discovery or getting msid etc is mentioned.i know there are other tools for these like sed plugin or seutil etc but using these command can we perform any basic operations any idea?

**Comment by igaw** [comment]
No sorry, I don't have any examples, so far I haven't really played with this stuff. We started to collect some info in the wiki: 

  https://github.com/linux-nvme/nvme-cli/wiki 

Obviously contributions are highly appreciated. If figure something out, please update the wiki. The next person will thank you.
