### ISSUE TITLE
Support for passing in psk_ke/psk_dhe_ke

### ISSUE THREAD

**Issue by sekar-wdc** [linux-nvme/nvme-cli#2618]
Hi,

I was wondering if there is or will be support for selecting the PSK key exchange mode (psk_ke/psk_dhe_ke) when initiating an NVMe/TCP TLS connection. It appears gnuTLS, which ktls-utils uses, supports both key exchange modes (psk_ke/psk_dhe_ke) but I don't see a way to select this via nvme-cli upon initiating a NVMe/TCP connection with TLS.

![image](https://github.com/user-attachments/assets/f614ae37-5897-45ea-99b6-d29f714946b6)

**Comment by igaw** [comment]
Depends what the spec says.  I have a hard time to figure out what we are supposed to do

![image](https://github.com/user-attachments/assets/a96c3fd3-faa0-4eed-bd7f-95146fa7ce2f)

Is it mandatory to support both or can we choose? Anyway, it's a question what the spec wants us to do. 
@hreinecke do you have some input on this one?

**Comment by sekar-wdc** [comment]
I think the spec does not allow it. I was thinking if there was a way to bypass the check but that does not seem possible.  Okay with closing this given the spec disallows it.

**Comment by igaw** [comment]
Okay, let's close it then. And I suspect the storage vendors will use the Linux implementation to tests against, so if it doesn't implement/support it, no target will support it either :)
