### ISSUE TITLE
wdc-smart-add-log contains incorrect output description

### ISSUE THREAD

**Issue by tim-oleksii** [linux-nvme/nvme-cli#270]
-o description is not consistent throught documentation. 'human' must be 'normal'.

**Comment by minwooim** [comment]
Hi Oleksii,
I have fixed what you reported to this issue by a commit 66f92fe.
If this patch is picked up, you will see correct output-format description in documents.

Thanks for your reporting.

**Comment by tim-oleksii** [comment]
Thx! This is great.

**Comment by keithbusch** [comment]
Fix is now committed, thanks, Minwoo!
