### ISSUE TITLE
wdc smart-log-add: duplicate output "Host Write Odd Start Commands"

### ISSUE THREAD

**Issue by zhangzujian** [linux-nvme/nvme-cli#285]
In funcitons wdc_print_log_json() & wdc_print_log_normal().

**Comment by tim-oleksii** [comment]
#286 is to fix it.

**Comment by tim-oleksii** [comment]
Pull request is suspended till someone from WDC make a review.

**Comment by jeffreyalien** [comment]
I reviewed the parts and agree it makes sense to remove the duplicate Host Write Odd Start Commands entry.

**Comment by tim-oleksii** [comment]
Is it OK to be closed?

**Comment by keithbusch** [comment]
Yep, it's pulled.

**Comment by jeffreyalien** [comment]
Yep, I agree; it can be closed.

Jeff Lien
