### ISSUE TITLE
nvme-cli: sign aware json output

### ISSUE THREAD

**Issue by tim-oleksii** [linux-nvme/nvme-cli#287]
It'd be great to adjust json according to recent addition of json_object_add_value_uint.

**Comment by minwooim** [comment]
Hello Tim,  

Please see following commit 8a6c5272daa71fd2d89bfeb5f469edb13092edbb.

**Comment by tim-oleksii** [comment]
Hello Minwoo,

Thanks for a notification!

Best regards,
tim-oleksii
