### ISSUE TITLE
Any roadmap for nvme-cli porting on ARM architectures? Is it currently possible compiling for arm?

### ISSUE THREAD

**Issue by melqu1ades** [linux-nvme/nvme-cli#288]
I'm interested in using nvme-cli in development platforms featuring ARM processors (HiKey960 is an example).

**Comment by keithbusch** [comment]
I don't have an ARM machine to test on, but I could swear it works there, or at least used to. What's the first problem you're encountering with it?

**Comment by melqu1ades** [comment]
Hi Keith,
thank you for your feedback.
I've gone thorough the Makefile that comes with nvme-cli and I found no references to any ARM compilation.Can you give me directions about how to compile nvme-cli on ARM architecture?
If you are involved in nvme-cli development and you're interested to cover also ARM compilation, I can provide you with a HiKey960 board to validate your code.Consider that also Automotive market is switching to NVMe drives, and many infotainment systems are ARM based.
Thanks for your support,Guglielmo 

----Messaggio originale----

Da: notifications@github.com

Data: 25-gen-2018 16.40

A: "linux-nvme/nvme-cli"<nvme-cli@noreply.github.com>

Cc: "melqu1ades"<guglielmo.ciavorella@tin.it>, "Author"<author@noreply.github.com>

Ogg: Re: [linux-nvme/nvme-cli] Any roadmap for nvme-cli porting on ARM architectures? Is it currently possible compiling for arm? (#288)




I don't have an ARM machine to test on, but I could swear it works there, or at least used to. What's the first problem you're encountering with it?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/linux-nvme/nvme-cli","title":"linux-nvme/nvme-cli","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/linux-nvme/nvme-cli"}},"updates":{"snippets":[{"icon":"PERSON","message":"@keithbusch in #288: I don't have an ARM machine to test on, but I could swear it works there, or at least used to. What's the first problem you're encountering with it?"}],"action":{"name":"View Issue","url":"https://github.com/linux-nvme/nvme-cli/issues/288#issuecomment-360504551"}}}

**Comment by tim-oleksii** [comment]
I was wondering whether you need to compile the tool in ARM host or just cross-compile in x86 PC into ARM executable?

**Comment by keithbusch** [comment]
Are you building on the target machine, or cross compiling? If on target machine, just running 'make' should work. If cross compiling, you need to set up the environment before running 'make'.

**Comment by melqu1ades** [comment]
Thank you.
The system I'm running experiment is the following:
Linux hikey960 4.14.0-rc7-linaro-hikey960 #1 SMP PREEMPT Fri Nov 24 10:45:34 UTC 2017 aarch64 aarch64 aarch64 GNU/Linux
I'm having troubles with nvme driver management: perhaps I need to recompile kernel.When solved I'll follow your suggestion.I'll be back to you in case of additional help need.
Thanks a lot to you all.
Regards,Guglielmo



----Messaggio originale----

Da: notifications@github.com

Data: 29-gen-2018 16.58

A: "linux-nvme/nvme-cli"<nvme-cli@noreply.github.com>

Cc: "melqu1ades"<guglielmo.ciavorella@tin.it>, "Author"<author@noreply.github.com>

Ogg: Re: [linux-nvme/nvme-cli] Any roadmap for nvme-cli porting on ARM architectures? Is it currently possible compiling for arm? (#288)



Are you building on the target machine, or cross compiling? If on target machine, just running 'make' should work. If cross compiling, you need to set up the environment before running 'make'.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/linux-nvme/nvme-cli","title":"linux-nvme/nvme-cli","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/linux-nvme/nvme-cli"}},"updates":{"snippets":[{"icon":"PERSON","message":"@keithbusch in #288: Are you building on the target machine, or cross compiling? If on target machine, just running 'make' should work. If cross compiling, you need to set up the environment before running 'make'."}],"action":{"name":"View Issue","url":"https://github.com/linux-nvme/nvme-cli/issues/288#issuecomment-361291482"}}}

**Comment by melqu1ades** [comment]
Hi Keith,
here I am back to this task.
I apologize for the long lasting issue.
I have now two **Hikey960** that I use as follows:
- system (Hikey960) with Linaro Linux (my build system) where

**Comment by wushgit** [comment]
Hi, @melqu1ades 

    I have a same requirement as you , need a nvme-cli tool can be used on an ARM board with Android. Can I have your solution?

**Comment by igaw** [comment]
nvme-cli 2.x build on ARM. We have CI cross builds for this arch:

https://github.com/linux-nvme/nvme-cli/blob/137fb15a285c060789581fc074ab3b1f6b250188/.github/workflows/build.yml#L28

Obviously, the build depends on a proper distribution such Debian. Currently, we don't have any CI builds enabled for more embedded systems based on buildroot or Yocto.
