### ISSUE TITLE
Question for the plan of patch submission process of nvme-cli.

### ISSUE THREAD

**Issue by minwooim** [linux-nvme/nvme-cli#298]
Hi Keith, and Folks,

Earlier, I have sometimes submitted few patches to linux-nvme mailing list to be reviewed by many developers and Keith has confirmed or accepted them. But CONTRIBUTING.md says that code contributions would be done by fork and merge workflow. Additionally, I have seen Keith wrote that _linux-nvme_ mailing list would be good to be used for nvme-cli because a lot more people subscribe it from Pull Request #282.

I'm afraid that I might disturb you guys because of improper places for submitting patches.
I really don't want to be a bother.

Keith, I would really appreciate it if you would let me know what is the plan for the process of patch submission on nvme-cli.

Sincerely,

Minwoo Im

**Comment by keithbusch** [comment]
Trivial patches can be sent as pull requests and I don't think anyone would mind. Anything substantial should probably go through the linux-nvme mailing list, but I am not super strict.
