### ISSUE TITLE
Source headers need updating to GPL 2.0?

### ISSUE THREAD

**Issue by hyandell** [linux-nvme/nvme-cli#30]
I notice that https://github.com/linux-nvme/nvme-cli/commit/3fdbf125a2448a52a64d40dd46923ce223871aa9 changed the LICENSE file to GPL 2.0. 

Should the source headers of these 7 files have been updated too?

https://github.com/linux-nvme/nvme-cli/search?utf8=%E2%9C%93&q=%22Apache+License%22

**Comment by hyandell** [comment]
Pull request opened with proposed fix for the files:

https://github.com/linux-nvme/nvme-cli/pull/32

**Comment by sbates130272** [comment]
Added the last two files with 6cf8b27bc1ce4982cec6640f4e7e4610795abe13.
