### ISSUE TITLE
Nvme-cli compile error with SPDK

### ISSUE THREAD

**Issue by sdfsdfsdxx2** [linux-nvme/nvme-cli#319]
I am using the latest code and I have built the spdk already. But I always encounter these errors when I tried  to build nvme-cli:

/home/cordite/Desktop/new_nvme/new/nvme-cli/spdk/dpdk/build/lib/librte_eal.a(eal_memory.o): In function `rte_eal_hugepage_init':
eal_memory.c:(.text+0xa28): undefined reference to `numa_allocate_nodemask'
eal_memory.c:(.text+0xa34): undefined reference to `numa_available'
eal_memory.c:(.text+0xa79): undefined reference to `get_mempolicy'
eal_memory.c:(.text+0xcce): undefined reference to `numa_bitmask_free'
eal_memory.c:(.text+0xd9f): undefined reference to `numa_allocate_nodemask'
eal_memory.c:(.text+0xdab): undefined reference to `numa_available'
eal_memory.c:(.text+0x10e8): undefined reference to `numa_bitmask_free'
eal_memory.c:(.text+0x234e): undefined reference to `set_mempolicy'
eal_memory.c:(.text+0x237e): undefined reference to `numa_set_localalloc'
eal_memory.c:(.text+0x24c5): undefined reference to `numa_set_preferred'
eal_memory.c:(.text+0x28ab): undefined reference to `numa_bitmask_free'
/home/cordite/Desktop/new_nvme/new/nvme-cli/spdk/dpdk/build/lib/librte_eal.a(eal_common_options.o): In function `eal_plugins_init':
eal_common_options.c:(.text+0x7d8): undefined reference to `dlopen'
eal_common_options.c:(.text+0x7e9): undefined reference to `dlerror'
collect2: error: ld returned 1 exit status
Makefile:41: recipe for target 'nvme' failed
make: *** [nvme] Error 1

**Comment by keithbusch** [comment]
What does this project have to do with SPDK?
