### ISSUE TITLE
nvme create-ns uses incorrect nsize on 32-bit systems if nsize is large

### ISSUE THREAD

**Issue by vimmanuel** [linux-nvme/nvme-cli#330]
On a 3.84TB SSD, the following command: 
nvme create-ns /dev/nvme0 -s 0x1bf1f72b0 -c 0x1bf1f72b0 -f 0 -m 1
creates a namespace of capacity 0xbf1f72b0. The 0x1 in the upper 32-bits is dropped.

Using long long instead of long fixed the issue, in argconfig.c, around line 288,
			*((long long *)value_addr) = suffix_binary_parse(optarg);

**Comment by keithbusch** [comment]
You're right, thanks for the head's up.
