### ISSUE TITLE
Firmware slot detection

### ISSUE THREAD

**Issue by narasimhan-v** [linux-nvme/nvme-cli#332]
Can someone please let me know if there is a way to detect firmware slots ?
I can see that there are 3 slots supported, but only one is seen.

```
# nvme fw-log /dev/nvme1
Firmware Log for device:nvme1
afi  : 0x11
frs1 : 0x51334234414e5047 (GPNA4B3Q)
#

# nvme fw-download /dev/nvme1 --fw=<image>
Firmware download success
# nvme fw-activate /dev/nvme1 -a 0 -s 1
NVME Admin command error:FIRMWARE_SLOT(106)
 
# nvme id-ctrl /dev/nvme1 -H | grep Firmware
[4:4] : 0x1   Firmware Activate Without Reset Supported
[3:1] : 0x3   Number of Firmware Slots
[0:0] : 0x1   Firmware Slot 1 Read-Only
```

**Comment by keithbusch** [comment]
Your controller says firmware slot 1 is read only, and you're trying to activate a new image into that read-only slot.

**Comment by keithbusch** [comment]
If you're asking why fw-log doesn't show the other slots, it's because you don't have anything valid in those slots for the program to show you.

**Comment by narasimhan-v** [comment]
@keithbusch That is right, It is read only. But I have seen in controllers where they only show one slot, and when we try to fw-activate on the other slots, they become visible. So, is that the way ?

**Comment by keithbusch** [comment]
The program is just the messenger. If you want to see firmware in any particular available slot, you need to put firmware in that slot so the device has something to report that the program can show you.

**Comment by got777888** [comment]
![Screenshot_20210726-150912_Termux](https://user-images.githubusercontent.com/87970064/126955482-cf38ca43-8713-433c-a73f-10efb9339103.jpg)
Tolong Bantu saya untuk Memecahkan masalah login ini, Saya tidak mengetahui user name dan Password nya
