### ISSUE TITLE
namespace overprovisioning

### ISSUE THREAD

**Issue by aTanCS** [linux-nvme/nvme-cli#343]
Hi. Is it possible to create bigger spare capacity (wear-leveling) for the whole controller or a namespace? Eg. setting capacity smaller then size? As it is possible with ATA SSD and hdparm -Np.

**Comment by keithbusch** [comment]
Not per-spec. This is feature is vendor specific and would have to fall under a vendor specific extension/plug-in if that vendor wants this feature to be conveniently reachable through this tool.

**Comment by igaw** [comment]
No progress in this bug report for a long time. If you think it's still relevant please reopen.
