### ISSUE TITLE
Mismatch between nvme-cli rpm package name available on github repository and Linux repository

### ISSUE THREAD

**Issue by Shadiasd** [linux-nvme/nvme-cli#348]
Hi,

Looking at the "nvme.spec.in" file available on this github repo, I noticed that the nvme-cli rpm package name is called "nvme" while the version available on linux repository is called "nvme-cli". 

I have an application that checks for nvme-cli dependency during its rpm installation. However, if I have the nvme-cli rpm installed from the version available on github (with the rpm package name "nvme"), my application fails to pass the dependency check due to this naming mismatch, because it simply cannot find any package called "nvme-cli".

I was wondering if (1) there is any fundamental reason behind having this rpm package name difference between the version available on github and linux repo? (2) is there a simple way to change the nvme-cli rpm package name for the github version to "nvme-cli"?

Thank you for your help,
Shadi

**Comment by Shadiasd** [comment]
To answer my second question, I was able to locally change the package name to "nvme-cli to be consistent across nvme-cli package available in linux repo and the one on github by making minor modifications to the spec file and Makefile.

However, I am still wondering why there is a package name mismatch between the github version and the distributed version in linux repo?

Thanks,
Shadi

**Comment by igaw** [comment]
No progress in this bug report for a long time. If you think it's still relevant please reopen.
