### ISSUE TITLE
add cls and nlw to Intel id-ctrl

### ISSUE THREAD

**Issue by hemiant** [linux-nvme/nvme-cli#349]
Please add Intel Vendor Specific to intel id-ctrl:
- Current PCIe Link Speed field (CLS)
- Negotiated Link Width (NLW)

You can see I added four new lines below in to intel_id_ctrl:
- json_object_add_value_int(root, "cls", vs[24]);
- json_object_add_value_int(root, "nlw", vs[25]);
- printf("cls     : %d\n", vs[24]);
- printf("nlw     : %d\n", vs[25]);

`static void intel_id_ctrl(__u8 *vs, struct json_object *root)
{
        char bl[9];
        char health[21];

        memcpy(bl, &vs[28], sizeof(bl));
        memcpy(health, &vs[4], sizeof(health));

        bl[sizeof(bl) - 1] = '\0';
        health[sizeof(health) - 1] = '\0';

        if (root) {
                json_object_add_value_int(root, "ss", vs[3]);
                json_object_add_value_string(root, "health", health[0] ? health : "healthy");
                json_object_add_value_string(root, "bl", bl);
        } else {
                printf("ss      : %d\n", vs[3]);
                printf("cls     : %d\n", vs[24]);
                printf("nlw     : %d\n", vs[25]);
                printf("health  : %s\n", health[0] ? health : "healthy");
                printf("bl      : %s\n", bl);
        }
}`

10x

**Comment by benreese0** [comment]
This can be closed now, right?
