### ISSUE TITLE
telemetry-log data is rounded by page size

### ISSUE THREAD

**Issue by tim-oleksii** [linux-nvme/nvme-cli#352]
I'm wondering why the tool rounds host telemetry content by page boundary?
If the size of a block is 512, we have extra undefined content dumped into file.
Are there any other concerns beside kernel driver size payload?

**Comment by ScottyBauer** [comment]
We have a patch coming to make 512.

**Comment by tim-oleksii** [comment]
This is great, thanks for a notification.

**Comment by keithbusch** [comment]
Looks like this is now updated.
