### ISSUE TITLE
nvme --list --output-format=json Non JSON output

### ISSUE THREAD

**Issue by paultop6** [linux-nvme/nvme-cli#358]
When running command nvme --list --output-format=json and there are no nvme devices detected, the output is a standard string of value "No NVMe devices detected." instead of standard JSON, like the following:
`{
  "Devices" : [ ]
}`

**Comment by keithbusch** [comment]
That's to stderr, though. That shouldn't get picked up by anything trying to consume json output, right?

**Comment by paultop6** [comment]
Double checked, its coming out stdout, and return code set to 0 (checked $?)

**Comment by keithbusch** [comment]
Hm? This is the line of code that's printing, right?

`fprintf(stderr, "no NVMe device(s) detected.\n");`

**Comment by paultop6** [comment]
Feel like a fool, was using an older version.  Tested the same scenario with 1.5 and no issues.  Will close issue now.
