### ISSUE TITLE
NVMe rubsystem-reset support and behaviour

### ISSUE THREAD

**Issue by narasimhan-v** [linux-nvme/nvme-cli#376]
I have an nvme subsystem which does not support subsystem-reset.
I suppose the NSSRC bit is the one which gives this information.

```
# nvme show-regs /dev/nvme0 -H | grep -i subsystem
	NVM Subsystem Reset Supported  (NSSRS): Yes
	NVM Subsystem Reset Occurred (NSSRO): No
	NVM Subsystem Reset Control (NSSRC): 0
```

But the `nvme subsystem-reset` command runs fine.
Isn't the command supposed to throw an error ? Or what is the expected behaviour ?

**Comment by narasimhan-v** [comment]
```
# nvme version
nvme version 1.2
```

**Comment by narasimhan-v** [comment]
But should that write check for the NSSRC bit ?

**Comment by keithbusch** [comment]
NSSRC is not a bit, and is defined by spec to always return 0 when read.

**Comment by keithbusch** [comment]
The kernel side implementation is a bit incomplete. Subsystem reset will take the link down, many ports don't report the link event for the driver to react to, so we end up with an unconfigured device.

**Comment by igaw** [comment]
No progress in this bug report for a long time. If you think it's still relevant please reopen.
