### ISSUE TITLE
Build error on Linux 4.16.7

### ISSUE THREAD

**Issue by JasonChiuCC** [linux-nvme/nvme-cli#377]
`nvme-print.c:1642:9: error: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 2 has type ‘uint64_t {aka long long unsigned int}’ [-Werror=format=]
  printf("\tThe timestamp is : %lu\n", int48_to_long(ts->timestamp));
`
Have to change from `%lu` to `%llu`

**Comment by tim-oleksii** [comment]
What's the version of gcc?

**Comment by JasonChiuCC** [comment]
`gcc (Ubuntu 5.3.1-14ubuntu2) 5.3.1 20160413
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
`

**Comment by keithbusch** [comment]
You're on a 32-bit host? Must use PRIu64 for this,
