### ISSUE TITLE
Additional SMART Log produces `NVMe Status:INVALID_LOG_PAGE(2109)`

### ISSUE THREAD

**Issue by iwittkau** [linux-nvme/nvme-cli#391]
```
$ sudo nvme list
Node             SN                   Model                                    Namespace Usage                      Format           FW Rev  
---------------- -------------------- ---------------------------------------- --------- -------------------------- ---------------- --------
/dev/nvme0n1     XXXXXXXXXXXXXXX      Samsung SSD 960 EVO 500GB                1         123,97  GB / 500,11  GB    512   B +  0 B   2B7QCXE7
```

```
$ sudo nvme --smart-log-add /dev/nvme0n1
NVMe Status:INVALID_LOG_PAGE(2109)
```

**Comment by keithbusch** [comment]
That's an optional, vendor specific log page. Most drives don't support it.

**Comment by iwittkau** [comment]
Wow, that was quick a quick answer, was still editing ... so this is not supported by my SSD?

**Comment by keithbusch** [comment]
Yeah, sounds like it isn't supported by your vendor.

**Comment by keithbusch** [comment]
It's an invalid log page. What more does a user want to see?

**Comment by keithbusch** [comment]
Note, a more recent version will use the error string defined in the specification in addition to the name of the status field, so it would look something like this:

"NVMe Status:INVALID_LOG_PAGE: The log page indicated is invalid. This error condition is also returned if a reserved log page is requested(2109)"

**Comment by iwittkau** [comment]
To me it just looked like `nvme` was broken or the drive support was inclomplete. `INVALID_LOG_PAGE` still seems like a very general error to me.  
If this is all based on a specification than it makes sense, I guess. Anyway, thanks for the great tool!
