### ISSUE TITLE
Intel SSD 750 Series NVMe drives are unable to be formatted with metadata sector layouts

### ISSUE THREAD

**Issue by excelero-joe** [linux-nvme/nvme-cli#392]
With the latest firmware releases included in the isdct package, the use of metadata extensions have been seemingly locked by a new flag which is preventing the ability of nvme-cli to use these LBA formats.  Perhaps this new required value is something to which Intel must speak.

Supporting info:

ISDCT Release:  isdct-3.0.13.400-17.x86_64
Example Drive Model: INTEL SSDPE2MW400G4
Drive Firmware: 8EV10174
Desired LBA Format: 4 KiB +  8 B (layout 4)

Because the command: `nvme format -l 4 /dev/nvme0n1` did not work, I was forced to use the Intel tool instead:

`isdct start -intelssd /dev/nvme0n1 -nvmeformat -namespace 1 LBAFormat=4 MetadataSettings=1`

The key part of the command is the `MetadataSettings=1` option as this seems to allow the special metadata format.

**Comment by excelero-joe** [comment]
I was just informed by some of my colleagues that the issue may also extend to the Intel DC P4500/P4510 model drives and perhaps others.  If this is the case, it may be true on the latest firmware for the entire NVMe line.

**Comment by keithbusch** [comment]
On a side note, I don't think there's a good use case for formats in Linux. Unless you want to run only the most basic device tests through the nvme ioctl, we don't have a good way to support interleaved metadata there.
