### ISSUE TITLE
'id-ctrl -H' Field Definitions

### ISSUE THREAD

**Issue by krishnanadh** [linux-nvme/nvme-cli#395]
Output fields of 'id-ctrl' like 'elpe', 'npss', 'tnvmcap', 'unvmcap' among others need definitions with the '-H' command option.

**Comment by keithbusch** [comment]
Those are all scalar values, and -H was meant for decoding bit-fields. What would you want -H to do for those?

**Comment by krishnanadh** [comment]
I see, understood. I was hoping -H could append for example the string "Unallocated NVM Capacity" for unvmcap.

**Comment by igaw** [comment]
No progress in this bug report for a long time. If you think it's still relevant please reopen.
