### ISSUE TITLE
Typo in nvme list command

### ISSUE THREAD

**Issue by abigail-climacosa** [linux-nvme/nvme-cli#396]
There is a typo in one of the attributes when using nvme list -o json.
Instead of MaximumLBA, it says MaximiumLBA

![typo](https://user-images.githubusercontent.com/25782619/43618488-83a2aa22-967d-11e8-9abc-378f4c2bc44f.png)

I am using nvme version 1.5.214.g7c61

**Comment by minwooim** [comment]
Hi Abigail,
Thanks for your reporting.  #397 will fix this issue.
