### ISSUE TITLE
nvme-list capacity wrong in v1.6 (is correct in v1.5)

### ISSUE THREAD

**Issue by herzlich** [linux-nvme/nvme-cli#405]
On IBM Power Red Hat Linux 7.5 
v1.6 the capacity shows incorrect value but shows correctly in v1.5.
Device is 4KB native block size.

v1.6: nvme list shows: Usage 97.68 MB / 97.68 MB - format: 1 B + 3073
nvme id-ctrl-> tnvmcap   : 400088457216

v1.5: nvme list shows: Usage 400.09 GB / 400.09 GB - format 4 KiB + 0 B
nvme id-ctrl -> tnvmcap   : 400088457216

I'm attaching log file toggling between v1.6 and v1.5.
[nvme-cli-v1.5--v1.6-IBM-ppc64-output.txt](https://github.com/linux-nvme/nvme-cli/files/2303037/nvme-cli-v1.5--v1.6-IBM-ppc64-output.txt)

**Comment by keithbusch** [comment]
Thanks for the notice, will get corrected ASAP. Sounds like an endian issue, but will confirm and fix.
