### ISSUE TITLE
nvme dsm command returns INVALID_OPCODE

### ISSUE THREAD

**Issue by erthalion** [linux-nvme/nvme-cli#408]
Hi,

I'm trying to use a `dsm` command, but it returns INVALID_OPCODE error:

```
$ cat /testfile
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

$ hdparm --fibmap /testfile

/testfile:
 filesystem blocksize 4096, begins at LBA 0; assuming 512 byte sectors.
 byte_offset  begin_LBA    end_LBA    sectors
           0     274432     274439          8

$ dd if=/dev/nvme0n1 skip=274432 count=1
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
1+0 records in
1+0 records out
512 bytes copied, 4.0323e-05 s, 12.7 MB/s

$ nvme dsm /dev/nvme0n1 --slbs=274432 --blocks=1 --idr
NVME IO command error:INVALID_OPCODE: The associated command opcode field is not valid(2001)
```

I tried to run it under gdb, but got not that much info - just an error after ioctl, and a cmd structure that was passed into it:

```
(gdb) p cmd
$13 = {opcode = 9 '\t', flags = 0 '\000', rsvd1 = 0, nsid = 1, cdw2 = 0, cdw3 = 0, metadata = 0, addr = 6672352, metadata_len = 0, data_len = 16, cdw10 = 0, cdw11 = 1, cdw12 = 0, cdw13 = 0,
  cdw14 = 0, cdw15 = 0, timeout_ms = 0, result = 0}
```
I'm trying this on EC2 (i3.2xlarge, so there should be real nvme), so I just want to figure out if it's a limitation of AWS or I'm using it wrong?

**Comment by keithbusch** [comment]
Please send the output of `nvme id-ctrl -H /dev/nvme0n1 | grep "Data Set Management"`

**Comment by erthalion** [comment]
```
$ nvme id-ctrl -H /dev/nvme0n1 | grep "Data Set Management"
  [2:2] : 0x1   Data Set Management Supported
```

**Comment by keithbusch** [comment]
Sounds like the controller your using has a firmware defect. The nvme-cli is just reporting what the controller returned to the requested command in this case, so if the controller claims to support DSM, then it shouldn't be an invalid opcode.

**Comment by erthalion** [comment]
Looks like the very same command works for other instance types, so it's indeed AWS EC2 problem.
