### ISSUE TITLE
How to get exit code after command?

### ISSUE THREAD

**Issue by seanmaster** [linux-nvme/nvme-cli#422]
Hi All, 
When I send a admin command, I got an error, I can use 'echo $?' to get return code, But! it just support one byte range. Such as below example:
I system namespace already attached.

# nvme attach-ns /dev/nvme0 -n 1 -c 0
NVMe Status:NS_ALREADY_ATTACHED(118)
# echo $?
24
So from example, I only get 0x18 status. How can I get Status Code Type (SCT) : 0x1, I need to know the error code belong to which SCT.

very thanks~

**Comment by keithbusch** [comment]
The exit status the shell reads is 8 bits. The NVMe SCT bit exists in bits 9 - 11.
