### ISSUE TITLE
no 'nottest' module

### ISSUE THREAD

**Issue by jk78346** [linux-nvme/nvme-cli#424]
After running "make run", it keeps saying that 
  **File "nvme-cli/tests/nvme_test.py", line 71, in TestNVMe
    @tools.nottest
AttributeError: 'module' object has no attribute 'nottest'**
I have no idea why this error comes out here.

**Comment by Okisa123** [comment]
What revision of Python did you use?

**Comment by jk78346** [comment]
python2.7, since python3 will have compiling issues.

**Comment by keithbusch** [comment]
Maybe need to update your version of python 'nose'?

**Comment by igaw** [comment]
No progress in this bug report for a long time. If you think it's still relevant please reopen.
