### ISSUE TITLE
get feature Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by seanmaster** [linux-nvme/nvme-cli#426]
When send below command , I got a segmentation fault.
# nvme get-feature /dev/nvme0 -f 0xc -H -s 3
get-feature:0xc (Autonomous Power State Transition), Supported capabilities value:0x000005
	Autonomous Power State Transition Enable (APSTE): Enabled
	Auto PST Entries	.................
	Entry[ 0]   
	.................
Segmentation fault (core dumped)

**Comment by keithbusch** [comment]
The code apparently is not handling the "Select field" correctly.  Will get a fix in shortly.

**Comment by keithbusch** [comment]
Should be good now.
