### ISSUE TITLE
json output of nvme identify is failing for more than 4TB drive

### ISSUE THREAD

**Issue by visheshvijay** [linux-nvme/nvme-cli#427]
Hi,
identify command 
"nvme id-ctrl /dev/nvme0 -o json" gets passed for 1TB and 2TB drive.

But it gets failed for 4TB drive.
nvme id-ctrl /dev/nvme0 -o json| grep -i tnvmcap
Allocation of memory for json object failed, aborting.

Could you please look into this ?

-Vishesh

**Comment by keithbusch** [comment]
Hmm... seems to work for me.  Are you using most current version?

**Comment by keithbusch** [comment]
no idea, working fine on drives of all capacities on my machine. could you send the ouptut of id-ctrl on such a drive in non-json format?
