### ISSUE TITLE
Supporting NVMe commands through SCSI tunnelling

### ISSUE THREAD

**Issue by hjmallon** [linux-nvme/nvme-cli#437]
Some devices support tunnelling NVMe commands through SCSI.

* Some Samsung NVMe devices support passing NVMe commands through the Security Send/Recv SCSI commands.
* USB / NVMe bridges are available, which may start supporting similar technology

What would be the best way to implement an alternative command to nvme_submit_passthru etc in nvme-ioctl.c? Has anyone had ideas on an architecture?

It would involve some repacking of the command into a SCSI command. Similar to how SAT works for SATA passthrough over SCSI.

I should be able to help out with this.

**Comment by keithbusch** [comment]
The kernel doesn't support this.

**Comment by hjmallon** [comment]
Yes, we would have to have a layer on top of the submit_passthrough commands in nvme-cli itself to either resolve to nvme ioctls (for normally attached ones), or scsi ioctls (for SCSI attached ones with tunnelling capability).

**Comment by keithbusch** [comment]
Let me make sure I understand what you're saying. Some vendor created an abomination that looks like SCSI to the host, but it's really NVMe?

**Comment by hjmallon** [comment]
A valid example would be NVMe disks in a USB->NVMe dock. JMicron and Asmedia are now manufacturing chips for this and I believe major brands are producing Portable SSDs based on those chips.

Those chips may provide interfaces to pass NVMe commands raw to the device, but the raw commands need to be wrapped up in SCSI to be sent.

So the nvme-cli, which has loads of knowledge and code to create NVMe commands, could have another backend (other than just the current NVMe ioctls) to send commands via these devices.

**Comment by keithbusch** [comment]
The driver creates the nvme commands, not nvme-cli. The tooling just creates arguments for the driver's ioctl. Things like command tagging and DMA setup required for an nvme command are outside user space's view. The only thing nvme-cli can readily accomplish here is decoding returned structures.

So I think you still need a kernel side implementation first for something like this to work, but even then, that sounds like it needs to go in some vendor specific extension unless T10 standardizes something (but I hope they stay away from nvme).

**Comment by hjmallon** [comment]
A kernel implementation is a possibility, providing those NVMe ioctls on the non-nvme devices. However a userspace implementation is also possible, which makes a kernel implementation sort of unlikely I think.

I understand your opinion on T10, but it would be nice to have some standard way to talk NVMe to portable USB SSD devices. Maybe nvmexpress will produce some kind of suggested way to do it, thereby avoiding having 100s of vendor specific ways to do it.

**Comment by keithbusch** [comment]
I'm not saying the kernel has to implement your desired feature, but there is definitely a kernel component that is required to support this. These would have to be bi-directional commands, right? Data-out to send the NVMe command, and data-in for the returned data? Those are non-trivial to set up, so you'd need some level of kernel support to facilitate it.

**Comment by hjmallon** [comment]
This code is incomplete and for Windows, but you can see how Samsung have implemented it here.

https://www.naraeon.net/en/samsung-nvme-passthrough-sample-cpp/

**Comment by keithbusch** [comment]
My corporate firewall thinks that link is an information security threat.

**Comment by hjmallon** [comment]
I have copypasted the code in above to workaround firewall issues.

**Comment by keithbusch** [comment]
Eww, that's even worse than I imagined. It's all vendor specific nonsense, there's nothing NVMe about it at all. They can't even get the code comments labeling CBD's correctly, and it appears to have an unenforced fused operation that will fall apart under any real usage.

If anyone really wants this sort of crap, get it standardized first.

**Comment by starkdm** [comment]
> This code is incomplete and for Windows, but you can see how Samsung have implemented it here. It can all be done with multiple SCSI passthrough commands constructed in userspace and sent with SCSI ioctls.
> 
> EDIT: Code copied from link inline to avoid firewall issues
> 
> ```c++
> #include <windows.h>
> #include <Ntddscsi.h>
> #include <tchar.h>
>     
> const TCHAR* SamsungTestPath = _T("\\\\.\\PhysicalDrive4");
>     
> struct SPTWith512Buffer {
>     SCSI_PASS_THROUGH Spt;
>     unsigned char SenseBuf[24];
>     unsigned char DataBuf[512];
> };
>     
> void SamsungNVMeIdentify(const TCHAR* Path) {
>     SPTWith512Buffer sptwb;
>     HANDLE hIoCtrl = CreateFile(Path, GENERIC_READ | GENERIC_WRITE,
>         FILE_SHARE_READ | FILE_SHARE_WRITE, NULL, OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, 0);
>     DWORD dwReturned;
>     size_t length;
>     BOOL bRet;
>     
>     // ---- SENDING PART ---- //
>     ZeroMemory(&sptwb, sizeof(SPTWith512Buffer));
>     
>     sptwb.Spt.Length = sizeof(SCSI_PASS_THROUGH);
>     sptwb.Spt.PathId = 0;
>     sptwb.Spt.TargetId = 0;
>     sptwb.Spt.Lun = 0;
>     sptwb.Spt.SenseInfoLength = 24;
>     sptwb.Spt.DataTransferLength = IDENTIFY_BUFFER_SIZE;
>     sptwb.Spt.TimeOutValue = 2;
>     sptwb.Spt.DataBufferOffset = offsetof(SPTWith512Buffer, DataBuf);
>     sptwb.Spt.SenseInfoOffset = offsetof(SPTWith512Buffer, SenseBuf);
>     
>     sptwb.Spt.CdbLength = 16;
>     sptwb.Spt.Cdb[0] = 0xB5; // SECURITY PROTOCOL IN
>     sptwb.Spt.Cdb[1] = 0xFE; // Samsung Protocol
>     sptwb.Spt.Cdb[3] = 5;    // Identify
>     sptwb.Spt.Cdb[9] = 0x40; // Transfer Length
>     sptwb.Spt.DataIn = SCSI_IOCTL_DATA_OUT;
>     sptwb.DataBuf[0] = 1;
>     
>     length = offsetof(SPTWith512Buffer, DataBuf)
>         + sptwb.Spt.DataTransferLength;
>     
>     bRet = DeviceIoControl(hIoCtrl, IOCTL_SCSI_PASS_THROUGH,
>         &sptwb, length, &sptwb, length, &dwReturned, NULL);
>     
>     // ---- RECEIVING PART ---- //
>     ZeroMemory(&sptwb, sizeof(SPTWith512Buffer));
>     
>     sptwb.Spt.Length = sizeof(SCSI_PASS_THROUGH);
>     sptwb.Spt.PathId = 0;
>     sptwb.Spt.TargetId = 0;
>     sptwb.Spt.Lun = 0;
>     sptwb.Spt.SenseInfoLength = 24;
>     sptwb.Spt.DataTransferLength = IDENTIFY_BUFFER_SIZE;
>     sptwb.Spt.TimeOutValue = 2;
>     sptwb.Spt.DataBufferOffset = offsetof(SPTWith512Buffer, DataBuf);
>     sptwb.Spt.SenseInfoOffset = offsetof(SPTWith512Buffer, SenseBuf);
>     
>     sptwb.Spt.CdbLength = 16;
>     sptwb.Spt.Cdb[0] = 0xA2; // SECURITY PROTOCOL IN
>     sptwb.Spt.Cdb[1] = 0xFE; // Samsung Protocol
>     sptwb.Spt.Cdb[3] = 5;    // Identify
>     sptwb.Spt.Cdb[9] = 0x40; // Transfer Length
>     sptwb.Spt.DataIn = SCSI_IOCTL_DATA_IN;
>     
>     length = offsetof(SPTWith512Buffer, DataBuf)
>         + sptwb.Spt.DataTransferLength;
>     
>     bRet = DeviceIoControl(hIoCtrl, IOCTL_SCSI_PASS_THROUGH,
>         &sptwb, length, &sptwb, length, &dwReturned, NULL);
> }
>     
> int main() {
>     SamsungNVMeIdentify(SamsungTestPath);
> }
> ```
> 
> https://www.naraeon.net/en/samsung-nvme-passthrough-sample-cpp/

Will be NVME_IDENTIFY_CONTROLLER_DATA returned?

**Comment by hreinecke** [comment]
No way. nvme-cli is implemented according to the NVMe specification, and is _exclusively_ focused on NVMe commands.
We will not add other command types (like SCSI passthrough commands). Please check smartctl for that.

**Comment by keithbusch** [comment]
Yeah, smartctl does have support for some scsi targets that provide bridges to nvme backends, like jmicron and realtek. It's still vendor specific CDBs and still not something this tool intends to support.
