### ISSUE TITLE
Observing timing issue nvme format command

### ISSUE THREAD

**Issue by sujithshankar** [linux-nvme/nvme-cli#443]
Description:
A partitioned and in-use NVMe drive cannot be partitioned initially (as soon as it is mounted and busy)
However, wait idle for 4~5 mins and retry nvme format to observe a successful format.

Setup:
Ubuntu 18.04.1 installed on a local hard disk (sda) and a separate NVMe data-disk.

Version details:
kernel - 4.15.0-43-generic 
nvme-cli version 1.5

Steps:
1. Create a partition (fdisk /dev/nvme0n1) 
2. Create a file system (mkfs.ext4 /dev/nvme0n1p1) 
3. Mount the file system (mount /dev/nvme0n1p1 /mnt) 
4. Change directory to the mounted FS (cd /mnt) 
5. Attempt to perform a nvme format (nvme format /dev/nvme0 -n 1) --> Observe failure: NVME Admin command error:ABORT_REQ(7)

Give a break of ~5 mins (system is kept idle) in between step-4 and step-5 and retry nvme format to observe successful format.

* I gave a try with master branch of nvme-cli. Same behavior observed.

* nvme format is successful in RHEL-7.6 without any idle time introduced.

* Let me know if any specific logs are required.

* Could you let me know what might be contributing to this change in formatting behavior by introducing such idle?

**Comment by keithbusch** [comment]
It sounds like that's the return code coming from the device, and if so, that behavior would have to be implementation specific to your vendor.

Do you get that return code immediately, or is there a noticeable delay? The kernel driver uses the ABORT_REQ return code internally when it fakes a return from a non-responsive device, but we don't (or at least shouldn't) be returning the synthesized response back to user space.

Your test itself is probably going to cause some problems since it will wipe out filesystem data out from under the mounted partition. If that is your intention, that should be okay.

**Comment by sujithshankar** [comment]
>It sounds like that's the return code coming from the device, 
>and if so, that behavior would have to be implementation specific to your vendor.

Ok, that's a good point. 
Till now I had given a try on two machine both having different Samsung PM1725a NVMe drives. I will try with any Intel NVMe drive and update the results here.

>Do you get that return code immediately, or is there a noticeable delay?

Abort failure returns in a second.

>Your test itself is probably going to cause some problems since it will wipe out filesystem data out from under the mounted partition. If that is your intention, that should be okay.

Yes, I am testing the nvme format feature.

**Comment by keithbusch** [comment]
Ok, definitely sounds like vendor specific behavior.

**Comment by sujithshankar** [comment]
Confirmed that behavior is specific to Samsung drives on Ubuntu 18.04.

However such failure behavior is not seen with RHEL 7.6/RHEL8.0 builds on Samsung drives.  
Any idea what might be contributing here?

**Comment by keithbusch** [comment]
Maybe different background tasks doing different access. Check with Samsung on how their drive operates, as the behavior you're describing is not aligned with any public spec guidance.
