### ISSUE TITLE
formate through nvme-cli is failing.

### ISSUE THREAD

**Issue by Naresh-ibm** [linux-nvme/nvme-cli#456]
I have a nvme device and while trying to formate it, it fails with following error.

linux-k0c4:~/nvme-cli-master/tests # nvme list
Node             SN                   Model                                    Namespace Usage                      Format           FW Rev  
---------------- -------------------- ---------------------------------------- --------- -------------------------- ---------------- --------
/dev/nvme0n1     S434NY0K100293       800GB NVMe Gen3 U.2 Slim SSD             1           0.00   B /  85.90  GB      4 KiB +  0 B   REV.MN37
/dev/nvme1n1     S434NY0K100290       800GB NVMe Gen3 U.2 Slim SSD             1          85.90  GB /  85.90  GB      4 KiB +  0 B   REV.MN37
linux-k0c4:~/nvme-cli-master/tests # nvme id-ctrl /dev/nvme0 -H | grep ^nn
nn        : 1
linux-k0c4:~/nvme-cli-master/tests #
linux-k0c4:~/nvme-cli-master/tests # nose2 nvme_format_test --verbose
/sys/devices/pci0013:70/0013:70:00.0/nvme/nvme0
nvme_format_test.TestNVMeFormatCmd.test_format_ns ... 20971520 20971520 0 0
nvme create-ns /dev/nvme0 --nsze=20971520 --ncap=20971520 --flbas=0 --dps=0

lba format 0 lbad       12 ms         0
20971520 20971520 0 0
nvme create-ns /dev/nvme0 --nsze=20971520 --ncap=20971520 --flbas=0 --dps=0
NVMe Status:NS_ID_UNAVAILABLE: The number of namespaces supported has been exceeded(2116)
FAIL

======================================================================
FAIL: nvme_format_test.TestNVMeFormatCmd.test_format_ns
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/nvme-cli-master/tests/nvme_format_test.py", line 139, in test_format_ns
    assert_equal(err, 0)
AssertionError: 22 != 0

----------------------------------------------------------------------
Ran 1 test in 32.820s

FAILED (failures=1)
linux-k0c4:~/nvme-cli-master/tests #

**Comment by visheshvijay** [comment]
Could you please give the output of controller identify ?
May be your device supports number of namespace = 1.
Script is trying to create NS even there is one NS present.

-Vishesh

**Comment by hreinecke** [comment]
Reporter has lost interest. Closing.
