### ISSUE TITLE
Nvme cli 1.7 build failure 

### ISSUE THREAD

**Issue by Gkavi2019** [linux-nvme/nvme-cli#457]
I am using cli version 1.7 and tried building on xenserver 6.5 , build fails, is there any minimum kernel version dependency

**Comment by keithbusch** [comment]
No kernel dependencies. There were a few arch specific errors in that tag, could you try the most current tip and see if it's resolved for you? If not, please include the build error output.

**Comment by keithbusch** [comment]
We okay now?
