### ISSUE TITLE
NVMe cmd fail with NVMeOF connection

### ISSUE THREAD

**Issue by ssanaifo** [linux-nvme/nvme-cli#461]
I'm complete NVMeOF RDMA connection.    (1 target - 1 host,    used Mellanox RDMA CARD)
but, when I issue cli command to target device (at host),   some command return wrong data and many command returned fail ( INVALID_OPCODE 4001).

For example,
1. nvme list  (FWRev show not FW version but target's Linux version 4.20.6.c)
                    (in Target PC FWRev show device's FW name correctly)
   Node             SN                   Model                                    Namespace Usage                      Format           FW Rev  
/dev/nvme0n1     1111111111     Linux                                    1         800.17  GB / 800.17  GB    512   B +  0 B   4.20.6.c
 
2. nvme smart-log (reterned data wrong)
                              (in Target PC show correctly)

Smart Log for NVME device:nvme0n1 namespace-id:ffffffff
critical_warning                    : 0
temperature                         : -273 C
available_spare                     : 0%
available_spare_threshold           : 0%
......
host_write_commands                 : 0
controller_busy_time                : 0

3. almost command failed  (in target Successfully completed)
  nvme format /dev/nvme0n1
NVME Admin command error:INVALID_OPCODE: The associated command opcode field is not valid(4001)

**Comment by keithbusch** [comment]
Smart is poorly supported on the linux target. The implementation is too abstracted from the hardware to provide accurate smart data.

Format is not supported at all, and both Command Effects log page and identify controller's OACS say as much.
