### ISSUE TITLE
Smart-log output units/descriptions

### ISSUE THREAD

**Issue by sachinkagarwal** [linux-nvme/nvme-cli#48]
Hi,

I am using the nvme-cli utility to read the smart-log off an NVME device. I was searching for descriptions of some of the parameters being reported. Here is my nvme smart-log output (below).

For example, I wanted to understand what data_units corresponds to (probably multiple kB from how much I wrote, but not sure what it is).

The context is that I am trying to write a monitoring script for NVMe cards that will invoke the smart-log command and report it for SSD wear/thresholds etc.

Apologies if this is not the right forum.

Thank you

-Sachin

user@node09:~$ sudo nvme smart-log /dev/nvme1n1 
Smart Log for NVME device:/dev/nvme1n1 namespace-id:ffffffff
critical_warning                    : 0
temperature                         : 34 C
available_spare                     : 100%
available_spare_threshold           : 10%
percentage_used                     : 0%
data_units_read                     : 203,913,228
data_units_written                  : 64,663,716
host_read_commands                  : 7,207,810,975
host_write_commands                 : 2,931,291,530
controller_busy_time                : 399
power_cycles                        : 9
power_on_hours                      : 742
unsafe_shutdowns                    : 5
media_errors                        : 0
num_err_log_entries                 : 0
Critical Composite Temperature Time : 0
Temperature Sensor 1                : 0 C
Temperature Sensor 2                : 0 C
Temperature Sensor 3                : 0 C
Temperature Sensor 4                : 0 C
Temperature Sensor 5                : 0 C
Temperature Sensor 6                : 0 C
Temperature Sensor 7                : 0 C
Temperature Sensor 8                : 0 C

**Comment by keithbusch** [comment]
See the "SMART / Health Log" section of the NVM Express specification. As of the latest version today, that is section 5.10.1.2 in spec version 1.2a. 

http://nvmexpress.org/wp-content/uploads/NVM-Express-1_2a.pdf
