### ISSUE TITLE
nvme-print: RFC about code clean-up

### ISSUE THREAD

**Issue by minwooim** [linux-nvme/nvme-cli#487]
Hi @keithbusch ,                                                               
                                                                               
I would like to ask about code-cleanup for nvme-print.[ch] files.  Here's my   
observation of nvme-print module.                                              
                                                                               
  1. There are two major types of functions with prefix show_ and json_.  I    
     can see a function with prefix print_ which needs to be consistant with   
     them.                                                                     
  2. nvme_[field]_to_string() functions are scattered.                         
  3. Few functions do not have any prefix to show what kind of functions are.  
  4. The actual sequence of function implementation is not the same in header  
     file.                                                                     
  5. Few functions have nvme command type such as:                             
       show_nvme_id_ctrl(), show_nvme_id_ctrl_sqes()                           
     but not for the other commands like:                                      
       nvme_feature_show_fields(), show_auto_pst()                             
                                                                               
                                                                               
If you agree on that it needs to be cleaned-up, then I would like to make them 
done.  However, if you think it's just churns for churns' sake, please let me  
know :)                                                                        
                                                                               
Thanks,

**Comment by keithbusch** [comment]
i'm starting this slow process now. i'll be more able to dedicate time now to reviewing cleanups, and writing more of these myself.
