### ISSUE TITLE
Makefile CFLAGS and LDFLAGS handling is problematic

### ISSUE THREAD

**Issue by amluto** [linux-nvme/nvme-cli#49]
For Fedora packages, the rules say that we have to set Fedora's preferred CFLAGS and LDFLAGS.  This breaks the Makefile: udev detection blows up.

An easy fix would be to do:

    	override LDFLAGS += -ludev
    	override CFLAGS  += -DLIBUDEV_EXISTS
    	override LIB_DEPENDS += udev

The "override" makes "make CFLAGS=whatever" not skip these assignments.

A nicer approach might be to use a different variable for the udev stuff or to support EXTRA_CFLAGS and EXTRA_LDFLAGS as alternatives to CFLAGS and LDFLAGS.

(It might also be nice to drop build-time udev detection entirely and just require udev.)

**Comment by keithbusch** [comment]
I'd like to also just make udev a requirement, but I know of users who's environments do not have it by default, and this program uses udev for only one non-essential command anyway.

I pushed the easy fix suggested. I also think we can do better than this, but incremental improvements are better than nothing.
