### ISSUE TITLE
Memory leaks in fabrics.c

### ISSUE THREAD

**Issue by kheitke** [linux-nvme/nvme-cli#505]
I've been running Infer against the CLI code and it has reported a few memory leaks that look legitimate. Most of these are in discover_from_conf_file()

fabrics.c:936: error: MEMORY_LEAK
  memory dynamically allocated by call to `calloc()` at line 922, column 10 is not reachable after line 936, column 7.
  934.
  935.                  err = argconfig_parse(argc, argv, desc, opts, &cfg, sizeof(cfg));
  936. >                if (err)
  937.                          continue;
  938.

fabrics.c:941: error: MEMORY_LEAK
  memory dynamically allocated by call to `calloc()` at line 922, column 10 is not reachable after line 941, column 10.
  939.                  err = build_options(argstr, BUF_SIZE);
  940.                  if (err) {
  941. >                        ret = err;
  942.                          continue;
  943.                  }

fabrics.c:947: error: MEMORY_LEAK
  memory dynamically allocated by call to `calloc()` at line 922, column 10 is not reachable after line 947, column 10.
  945.                  err = do_discover(argstr, connect);
  946.                  if (err) {
  947. >                        ret = err;
  948.                          continue;
  949.                  }

fabrics.c:932: error: MEMORY_LEAK
  memory dynamically allocated by call to `strdup()` at line 915, column 10 is not reachable after line 932, column 17.
  930.                  argc = 0;
  931.                  argv[argc++] = "discover";
  932. >                while ((ptr = strsep(&args, " =\n")) != NULL)
  933.                          argv[argc++] = ptr;
  934.
n

**Comment by keithbusch** [comment]
Fixing leaks is always good. It's never been a priority though as a this is just a one-shot program: everything it allocates is reclaimed immediately after the returning function forgot to free something, so a leak exists for maybe a few microseconds. We'd still like to fix them as they're found since we may want to turn this into a library, daemon, or run with longer running batches.
