### ISSUE TITLE
INVALID_FIELD(6002)

### ISSUE THREAD

**Issue by xiaobinggun** [linux-nvme/nvme-cli#542]
INVALID_FIELD: A reserved coded value or an unsupported value in a defined field(6002)
I want to know the specific meaning of 6002 error code, thank you!

**Comment by keithbusch** [comment]
To the spec, section 4.6.1!

0x6002 has DNR (Do Not Retry) and M (More) bits set (from the upper '6' value):
DNR: Retrying the same command will fail
M: More information about the failure may be found in the Error Log Page

SCT Field is 0, indicating it's a generic command status, and should use the generic status code table to decode the last byte, which is "02h".

02h: Invalid Field in Command: A reserved coded value or an unsupported value in a defined field(other than the opcode field). This status code should be used unless another status code is explicitly specified for a particular condition. The field may be in the command parameters as part of the Submission Queue Entry or in data structures pointed to by the command parameters.
