### ISSUE TITLE
[Question] Documentation Generation

### ISSUE THREAD

**Issue by sc108-lee** [linux-nvme/nvme-cli#577]
https://github.com/linux-nvme/nvme-cli/pull/576

same as upper PR's comment.

1 ) Question. Why does (.1, .html) files are included in git?
(if you want sustain Documentation policy same as now, Please check below suggestion)

2 ) Suggestion.
If there is no other reason to regenerate the Documentations, isn't it better to update when txt files are updated?
Because generation of .1 .html files makes change only for date or some versions (not related on original txt file), so I think its better to maintain the dates as a txt file updated day.
If this suggestion is accepted, txt file generator/modifier should update .1, .html files as well.
how does it sound?

**Comment by keithbusch** [comment]
They're just included so people can install without having the asciidoc dependency. I was repeatedly asked about this, so it saved me time to just include the built documentation and not have the default build rule try to generate them.
