### ISSUE TITLE
Wrong output value for a few of stat inquiry commands (such as smart-log), when using character device instead of the block device

### ISSUE THREAD

**Issue by Shadiasd** [linux-nvme/nvme-cli#585]
Hey,

I am using nvme_cli  `version 1.8.1`. I noticed that the following two commands results in different output values, although I think they are supposed to have the same output when drive has only one namespace:
- `sudo nvme  smart-log /dev/nvme0n1`
- `sudo nvme  smart-log /dev/nvme0`

The interesting part is that, it actually seems to show the output of `nvme1n1`  when I use the character device `nvme0` instead of the block device `nvme0n1` as part of the command. Similar output swapping is happening for all the other SSDs I have on the same machine.

I noticed the issue happens with some of the other commands such as `intel smart-logg-add`, `intel temp-stats`, and a few more. 

This issue does not exist on `nvme version 1.6`.

Thank you for looking into this issue and please let me know if you require additional information,
Shadi

**Comment by keithbusch** [comment]
/dev/nvme0 and /dev/nvme0n1 do not necessarily refer to the same device. See https://github.com/linux-nvme/nvme-cli/issues/510

Note, this will be addressed a bit better in kernel 5.4, and will be backported to all the LTS stables starting at 4.19.
