### ISSUE TITLE
nvme format fail

### ISSUE THREAD

**Issue by GitYuanQu** [linux-nvme/nvme-cli#600]
I try to erase NVMe SSD with secure mode, but it failed. detail as below:
============================
$nvme --version
nvme version 1.6
$nvme format -s 0 /dev/nvme0n1
[ 859.491564] nvme nvme0: Shutdown timeout set to 6 seconds
NVME Admin command error: INVALID_FORMAT: The LBA Format specified is not supported. This may be due to various conditions(410a)
============================
as I know, if I not specified the LBA through option --pi, LBA will use default value '0', so why the error message is show 'LBA Format specified is not supported'? actually I am not specified the LBA value. so could someone tell me what should I do to fix or workaround this issue? thanks.

**Comment by keithbusch** [comment]
Maybe your device doesn't support SES (the '`-s`' option). Check '`nvme id-ctrl /dev/nvme0n1 | grep fna`' and see if bit 2 is set.

**Comment by keithbusch** [comment]
Oh, you've -s 0, which should be the same as not setting -s at all... In that case, yeah, the program would use the previous lbaf the device is currently formatted with, which is supposed to always succeed. Sounds like you've a device specific, non-compliant firmware issue.

**Comment by GitYuanQu** [comment]
em... I wrote a error message, the actual command I've execute is "nvme format /dev/nvme0n1 -s 1", and the result as upper failed output.

**Comment by GitYuanQu** [comment]
I have check this device through command 'ls /dev/nvme*', it output as below:
==================
/dev/nvme0 /dev/nvme0n1 /dev/nvme0n1p1 /dev/nvme0n1p2 /dev/nvme0n1p3 /dev/nvme1 /dev/nvmen1
===================
I try the command "nvme id-ctrl /dev/nvme0n1 | grep fna", is shows as below:
=======================
fna   : 0x4
=======================

**Comment by GitYuanQu** [comment]
I even try to detach the namespace from /dev/nvme0 via execute command 'nvme detach-ns /dev/nvme0 -n 1 -c 0' and delete namespace through 'delete-ns /dev/nvme0 -n 1', but it all failed.
it shows status is NS_INSUFFICIENT_CAPACITY. so base on upper message, could you help me to know what occured on my device and how could I format it success, or do you have any workaround?

**Comment by GitYuanQu** [comment]
have someone could answer this? I am waitting...

**Comment by keithbusch** [comment]
Your controller's reported FNA says it supports secure erase on format options, so it should work either way.

I'm not sure what detaching the namespace was supposed to accomplish though. There really are not very many controllers/subsystems that support this behavior.

It really sounds like your device is not behaving in a compliant manner. Does an '`nvme format /dev/nvme0n1 -l 0`' succeed? That's the simplest type of format you can do.

**Comment by GitYuanQu** [comment]
unfortunatelly, I try to use command 'nvme format /dev/nvme0n1 -l 0/1/2/3', its all fails.

**Comment by keithbusch** [comment]
You should contact your device vendor.

**Comment by keithbusch** [comment]
closing as a device side issue

**Comment by benjaminrich** [comment]
I have the same issue. My device controller identifies as:

```
mn        : WDC PC SN520 SDAPNUW-256G-1002          
```

**Comment by Shekelme** [comment]
The same issue with WDS200T3X0C-00SJG0. On several computers it is possible to format them, but on one (Asus Pro WS WRX80E-SAGE SE WIFI, AMD 3995WX) it is not.

**Comment by keithbusch** [comment]
Without any vendor guidance, there doesn't appear to be anything we can do from the application side to unblock this operation from executing.

**Comment by tomty89** [comment]
[Hope you don't mind me spreading the possible solution]
See https://github.com/linux-nvme/nvme-cli/issues/816#issuecomment-834586681

**Comment by aggieNick02** [comment]
Please see my comment on this related issue [here](https://github.com/linux-nvme/nvme-cli/issues/84#issuecomment-2183511051). It covers what is happening, why the suspend/resume trick often works, and what you can do when it does not.
