### ISSUE TITLE
nvme read issue as picture attached

### ISSUE THREAD

**Issue by adeamlee** [linux-nvme/nvme-cli#602]
nvme read issue as picture attached。

if the size （-z）less than32， it works well；
or it crash as picture attached

please check.

**Comment by adeamlee** [comment]
nvme read /dev/nvme0n1 -s 0 -c 16 -z 128 -d read_0_2.bin

**Comment by adeamlee** [comment]
picture can not be uploaded

**Comment by adeamlee** [comment]
code as below for allocate memory buffer has issue, please check.

	if (posix_memalign(&buffer, getpagesize(), buffer_size)) {
		fprintf(stderr, "can not allocate io payload\n");
		err = ENOMEM;
		goto close_mfd;
	}

**Comment by keithbusch** [comment]
The command you are requesting to send is nonsense, I'm not surprised it crashes. The device is going to overrun the 128 byte buffer you requested to allocate for 17 blocks.

**Comment by adeamlee** [comment]
thanks a lot, i check the issue, the size also should be a multiple of 8 for that our test pc is 64bit Windows10.

**Comment by keithbusch** [comment]
Not just a multiple of 8. It should be a multiple of the block size, which is usually either 512 or 4096.
