### ISSUE TITLE
Protocol corresponding to 1.9

### ISSUE THREAD

**Issue by zb861359** [linux-nvme/nvme-cli#605]
Hi，where can I get the protocol corresponding to 1.9 version？

**Comment by keithbusch** [comment]
The versioning of this tool is independent of the specification.

**Comment by zb861359** [comment]
@keithbusch 
em...So which specification can I refer to in terms of version 1.9?
The most latest version of the specification is 1.4  on the official website.

**Comment by keithbusch** [comment]
Oh, always refer to the public spec latest, which is 1.4. We don't implement all the features from the spec, but we add them as devices we can test implement them.

**Comment by zb861359** [comment]
@keithbusch 
what do you mean of " we add them as devices we can test implement them."?

**Comment by keithbusch** [comment]
New features are added to the program when a device that also implements it exists. That way the code can actually be tested. If the nvme spec defines a feature that not a single nvme device implements, then we're not going to bother updating the tool for an unreachable feature.

**Comment by zb861359** [comment]
Is it means that there are nvme devices first, and then nvme programs? Whether this approach will affect the update iteration speed of nvme devices?

**Comment by keithbusch** [comment]
Yes. The vendors who make the devices have prototypes implementing spec features long before they're generally available, though, so programs are typically enabled ahead of the market.

What feature are you looking for anyway?

**Comment by zb861359** [comment]
I am looking for features of zoned namespace

**Comment by keithbusch** [comment]
> I am looking for features of zoned namespace

There is no ratified TP defining that, so such topics on public lists isn't appropriate. You should contact your nvme technical workgroup representative for such things.
