### ISSUE TITLE
NVMe status: INVALID_OPCODE: The associated command opcode field in not valid(0x6001)

### ISSUE THREAD

**Issue by danarellano** [linux-nvme/nvme-cli#627]
Version: nvme-1.9.143.g525a

`sudo nvme format -s1 /dev/nvme0n1`
`NVMe status: INVALID_OPCODE: The associated command opcode field in not valid(0x6001)`

`sudo systemctl -i suspend`
`sudo nvme format -s1 /dev/nvme0n1`
`NVMe status: INVALID_OPCODE: The associated command opcode field in not valid(0x6001)`

Any suggestions?

**Comment by keithbusch** [comment]
Your device is not correctly implementing the nvme protocol. There's nothing tooling can do about this, you can only complain to your vendor, or just purchase a more compliant drive.

**Comment by keithbusch** [comment]
Eh, it could still be compliant since Format NVM is listed as an optional command. Check '`nvme id-ctrl | grep oacs`' and see if bit 1 is set to confirm the device supports the command. If it is not set, then the device is correctly announcing that it doesn't support any type of format, and your only recourse is still to contact your vendor if you want this command implemented.

**Comment by danarellano** [comment]
`sudo nvme id-ctrl /dev/nvme0n1 | grep oacs`
result in:
`oacs         : 0x17`

0x **1** 7 
Does this confirm the devices supports the command?

**Comment by keithbusch** [comment]
Yes, that says format is supported. Sounds like a firmware bug to me. Either it needs to unset the bit or we shouldn't see that error status.

**Comment by maximbaz** [comment]
If your drive is made by Samsung, there is a known bug that results in this error, the workaround is to suspend your computer first (systemctl suspend), then resume, then try formatting again.

**Comment by deepakagrawal** [comment]
I also get 

```
sudo nvme id-ctrl /dev/nvme0n1 | grep oacs
result in:
oacs : 0x17

```

You mentioned `Either it needs to unset the bit or we shouldn't see that error status.` How do I do that? I tried suspending the system as well but no success.

**Comment by deepakagrawal** [comment]
> `sudo nvme id-ctrl /dev/nvme0n1 | grep oacs`
> result in:
> `oacs : 0x17`
> 
> 0x **1** 7
> Does this confirm the devices supports the command?

Were you able to solve this problem @danarellano

**Comment by keithbusch** [comment]
> You mentioned `Either it needs to unset the bit or we shouldn't see that error status.` How do I do that? I tried suspending the system as well but no success.

You don't do that. The vendor is supposed to do that because their implementation is broken.
