### ISSUE TITLE
Improve building of nvme-cli outside its source tree

### ISSUE THREAD

**Issue by raalkml** [linux-nvme/nvme-cli#635]
Take, for instance, this line:

https://github.com/linux-nvme/nvme-cli/blob/ddf4df9bd14c7cdb2e548c058d21c59ed2a9ebec/Makefile#L75

It references the source file (nvme.c) directly in the command instead of using Make special variable $<. Just replacing this file name with a variable makes it possible to build the nvme utility by setting VPATH and include directories.

To improve the "experience" even further, it would be nice to create the sub-directories of the object files, since the Makefile redefines the built-in commands anyway.

**Comment by keithbusch** [comment]
yes, good idea.

**Comment by igaw** [comment]
No progress in this bug report for a long time. If you think it's still relevant please reopen.
