### ISSUE TITLE
how to get status code type(SCT) from exit code

### ISSUE THREAD

**Issue by ryderhsu0129** [linux-nvme/nvme-cli#648]
I sent a IO command and got the following message:
`NVMe IO command error:unknown(4181)`

and I echo $? to got the status code(SC):
`129`

How do I get status code type(SCT) from the value 4181?thanks!

**Comment by keithbusch** [comment]
This format matches nvme cqe status field with the pase shifted out and printed in hex. In 0x4181, 4h is the "do not retry" flag, 1h is the status code type (what you're asking), and 81h (129 in decimal) is the status code.

**Comment by ryderhsu0129** [comment]
> This format matches nvme cqe status field with the pase shifted out and printed in hex. In 0x4181, 4h is the "do not retry" flag, 1h is the status code type (what you're asking), and 81h (129 in decimal) is the status code.

@keithbusch 
I get it.
thanks for your reply!
