### ISSUE TITLE
gp2 volume full

### ISSUE THREAD

**Issue by karthickrangan** [linux-nvme/nvme-cli#670]
Hello friends,

In aws we are using gp2 storage volume and right now it was full

iam using git bash please tell a cmd to get into the volume and delete some files.

please do the needful
![InkedWhatsApp Image 2020-02-27 at 11 02 33 PM (1)_LI](https://user-images.githubusercontent.com/61595490/75601398-a07de200-5ae0-11ea-8109-31479f909c69.jpg)

**Comment by keithbusch** [comment]
Sounds like generic filesystem question and nothing to do with nvme specifically. It says the nvme partition is your root filesystem. What trouble are you having navigating from '/' and identifying undesirable files to delete?

**Comment by karthickrangan** [comment]
Dear Keith,

i am using git bash tool to work with console
i need to delete some unwanted files in that root file system
what was the git bash cmd used to do that

**Comment by karthickrangan** [comment]
awaithing for yo reply keith

**Comment by keithbusch** [comment]
Sorry, your question has nothing to do with this project. I never heard of 'git bash'. It looks like a Windows tool, so this isn't the appropriate forums.
