### ISSUE TITLE
get-log -o

### ISSUE THREAD

**Issue by Baaraan** [linux-nvme/nvme-cli#710]
Hello,
I'm using nvme-cli version 0.5-1ubuntu0.2 (just updated) and when I try to read a specific offset of a log-page, I get this error:

```
get-log: unrecognized option '-o'
Usage: nvme get-log <device> [OPTIONS]

Retrieve desired number of bytes from a given log on a specified device in
either hex-dump (default) or binary format

Options:
  [  --namespace-id=<NUM>, -n <NUM> ]   --- desired namespace
  [  --log-id=<NUM>, -i <NUM> ]         --- identifier of log to retrieve
  [  --log-len=<NUM>, -l <NUM> ]        --- how many bytes to retrieve
  [  --raw-binary, -b ]                 --- output in raw format
```
Does that mean -o being removed, is that intentionally?

Thanks,
Maliheh

**Comment by keithbusch** [comment]
Not removed. The version you are using was released before log page offsets existed.

**Comment by Baaraan** [comment]
Thanks Keith, 
I was using the one built-in my Ubuntu and sure it was old.

**Comment by Baaraan** [comment]
Hi Keith,

Now that I've actually updated, get-log is all good,  but I have another problem with this new version:
nvme version 1.11.1.17.g46e0
Problem is nvme list does not show my nvme drive anymore while I'm pretty sure my drive is there happy and healthy:

`sudo lsblk`
`nvme0n1                       259:0    0     7T  0 disk`

`sudo nvme list`
`Failed to scan namespaces`

Any idea what I might be doing wrong or maybe someone else also has same problem with this version?

Thanks!

**Comment by keithbusch** [comment]
weird, what kernel version are you using?

**Comment by Baaraan** [comment]
Here:

4.10.0-28-generic #32~16.04.2-Ubuntu SMP Thu Jul 20 10:19:48 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Thanks for your time!

**Comment by Baaraan** [comment]
@keithbusch ,
FYI I've went back to  1.10.1 tag and now everything seems working again, so sure something in the latest, if you want I can make a new issue for this to be tracked?

**Comment by keithbusch** [comment]
Could you try pulling the latest and see if it works? Commit https://github.com/linux-nvme/nvme-cli/commit/f4f3fd2ea4b878fe38fd3409f374ded8d5b34a4c was just added that should address your 'list' sighting.

**Comment by Baaraan** [comment]
Yes, all good now :)
Thanks for the quick fix!
