### ISSUE TITLE
Local builds install to /usr/sbin instead of /usr/local/sbin

### ISSUE THREAD

**Issue by meaton82** [linux-nvme/nvme-cli#715]
This will cause a conflict between the local build and nvme-cli installed from package manager.

$ make
NVME_VERSION = 1.11.1.21.gd766
...
$ sudo make install
rm -f /usr/local/sbin/nvme
install -d /usr/sbin
install -m 755 nvme /usr/sbin
...

**Comment by keithbusch** [comment]
I don't think we have any control from this side how package managers bundle their installer.

**Comment by meaton82** [comment]
Okay just wanted to make sure this was expected behavior and not a bug.
