### ISSUE TITLE
Add Support for log 09h (5.14.1.9 Endurance Group Information)

### ISSUE THREAD

**Issue by gwendalcr** [linux-nvme/nvme-cli#730]
NVMe specification 1.4 adds Endurance Group information. It is an optional feature that provides per group endurance information. A NVMe device can contains several groups one for storing user data, another with better write performance. Namespaces are mapped through set to a given group.
[see presentation at https://www.flashmemorysummit.com/Proceedings2019/08-06-Tuesday/20190806_NVME-101B-1_Carlson.pdf]

**Comment by keithbusch** [comment]
Please see "nvme endurance-log --help"
