### ISSUE TITLE
with nvme version 1.12.78.gabde, the nvme connect is not re-attempted for 60 iterations (once every 10secs) after interface is down

### ISSUE THREAD

**Issue by govind-rathod1987** [linux-nvme/nvme-cli#783]
with nvme version 1.12.78.gabde, the nvme connect is not re-attempted for 60 iterations (once every 10 secs) after interface is down.

Note: In the earlier version of nvme-cli (1.10), we have seen that whenever an interface that has active NVMe connection is down, at the NVMe host it used to try reconnecting once every 10secs for 60 iterations.

Is there any change in the implementation of 1.12 version? or there is some other way to have that behavior?

command used for NVMe connect with nvme-cli 1.12 is:
 "nvme connect-all -w <host_ip> -t rdma  -a <Target_ip> -q <host_nqn> -i 8 -m"

**Comment by igaw** [comment]
No progress in this bug report for a long time. If you think it's still relevant please reopen.
