### ISSUE TITLE
what is function for doorbell stride

### ISSUE THREAD

**Issue by seedjack** [linux-nvme/nvme-cli#791]
hello，
I have a question，what is doorbell stride？
What situation will use it?

**Comment by keithbusch** [comment]
It defines a gap between the queue doorbells. The use cases are pretty niche, so we don't see it implemented often.

The example from the spec is about software emulation where you can separate doorbells by cache line, which then allows special CPU instructions to monitor individual queue access. Without a stride, the monitor would need additional overhead to determine which queue was updated.
