### ISSUE TITLE
nvme.1 (man page) is missing reference to nvme-reset.1

### ISSUE THREAD

**Issue by ofalk** [linux-nvme/nvme-cli#793]
Hi!

I recently recognized that the man-page of `nvme` has no reference to `nvme-reset`.

Links:
* https://github.com/linux-nvme/nvme-cli/blob/master/Documentation/nvme.1
* https://github.com/linux-nvme/nvme-cli/blob/master/Documentation/nvme-reset.1

It would be nice to see this low hanging fruit fixed.

I didn't check the txt and html files, but I guess the same is true there.

Thx!

**Comment by minwooim** [comment]
PR: https://github.com/linux-nvme/nvme-cli/pull/840

Thanks,

**Comment by hreinecke** [comment]
Pull request merged, closing.
