### ISSUE TITLE
Question: Use of -b with get-features commands

### ISSUE THREAD

**Issue by ahribeng** [linux-nvme/nvme-cli#808]
Question on using the --raw_binary opt when using get-features. Is raw binary supposed to return data back in binary format . Is it only applicable if the Feature uses a buffer?

![image](https://user-images.githubusercontent.com/22842249/93268384-eee38d00-f761-11ea-8189-68f8bfbd1b72.png)

**Comment by keithbusch** [comment]
Yes, just binary dumps from prp data and doesn't apply to data encoded within queue entries. Most of the features don't use data payloads.

**Comment by ahribeng** [comment]
@keithbusch Okay thanks for the info.
