### ISSUE TITLE
nvme-cli: command not found after installing 

### ISSUE THREAD

**Issue by cesarvspr** [linux-nvme/nvme-cli#842]
sudo apt-get install nvme-cli 

Just used the install command and nvme-cli still appears and not found when I try "nvme-cli"

**Comment by minwooim** [comment]
Please try it with "nvme" rather than "nvme-cli".

**Comment by keithbusch** [comment]
nvme-cli is the name of the repository and package, but the command executable is just 'nvme'.

**Comment by cesarvspr** [comment]
Worked, tks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
