### ISSUE TITLE
nvme get lba status command does not set nsid and data length

### ISSUE THREAD

**Issue by robinejoh** [linux-nvme/nvme-cli#848]
Dear maintainers,

According to NVMe 1.4 spec, 
when host issue get lba status valid namespace ID has to be specified,
but currently nvme cli does not receive namespace ID as an option for get lba status command. 

And, get lba status need to retrieve data buffer that the device transfers to host, 
but nvme cli does not set data length field when issue nvme_submit_admin_passthru, like below.

> int nvme_get_lba_status(int fd, __u64 slba, __u32 mndw, __u8 atype, __u16 rl, void *data)
{
	  struct nvme_admin_cmd cmd = {
		  .opcode =  nvme_admin_get_lba_status,
		  .addr = (__u64)(uintptr_t) data,
		  .cdw10 = slba & 0xffffffff,
		  .cdw11 = slba >> 32,
		  .cdw12 = mndw,
		  .cdw13 = (atype << 24) | rl,
	  };
	return nvme_submit_admin_passthru(fd, &cmd);
}

**Comment by ganaidu707** [comment]
@keithbusch I have fixed this issue, please check the PR
https://github.com/linux-nvme/nvme-cli/pull/866

**Comment by robinejoh** [comment]
@ganaidu707 , @keithbusch 
Now it is fixed, so I will close the issue.
