### ISSUE TITLE
Script to Check a Patch Satisfying min Coding Guidelines or Not

### ISSUE THREAD

**Issue by ganaidu707** [linux-nvme/nvme-cli#856]
Could you tell us like what are the guidelines does nvme-cli follows? 

We can have a script to check whether the given patch following certain guidelines.

> e.g: 1. 80 Character per line
> e.g: 2. If any white space characters check etc..

or it is already existed?

**Comment by keithbusch** [comment]
We've adopted the Linux kernel coding style, though they've been very loosely applied to the vendor extensions... I think the kernel's checkpatch.pl utility should work here.

**Comment by ganaidu707** [comment]
Yes that works here, but not able to find that checkpatch.pl utility here, can we pull it to this code base, so that before commit, we can verify coding guidelines.
