### ISSUE TITLE
NVME cli : Need to know if there is a way to get completion queue entry of the last NVMe command issued via nvme cli ?

### ISSUE THREAD

**Issue by vspvijay** [linux-nvme/nvme-cli#858]
Do we have a way to read NVMe device's completion queue entry using nvme cli ?

Here are steps done using nvme cli, version 1.6 & 1.9 shell> sudo nvme id-ctrl /dev/nvme0 ... ... This provides the nvme identify ctrl information for the selected device as per ask.

From the nvmecli command line options, not finding options to read the nvme device's completion queue entry for the last nvme command posted.

Any help is much appreciated.

Thanks.

**Comment by keithbusch** [comment]
The kernel does not return the entire CQE, so you can't get it through this interface. The kernel just returns parts of the CQE. The return value is the CQE's status field from DW3, and the "result" from DW0 is written into the ioctl's struct parameter. You can also get DW1 if using the 64-bit version of the ioctl.

The remaining fields are not provided to the user through this interface. You can probably snoop these with nvme trace events, though.

**Comment by vspvijay** [comment]
Thank you.
